# DO NOT EDIT THIS FILE!
#
# Python module CosQueryCollection generated by omniidl

import omniORB
omniORB.updateModule("CosQueryCollection")

# ** 1. Stub files contributing to this module
import CosQueryCollection_idl

# ** 2. Sub-modules

# ** 3. End
