# DO NOT EDIT THIS FILE!
#
# Python module CosLifeCycleReference generated by omniidl

import omniORB
omniORB.updateModule("CosLifeCycleReference")

# ** 1. Stub files contributing to this module
import CosLifeCycleReference_idl

# ** 2. Sub-modules

# ** 3. End
