# DO NOT EDIT THIS FILE!
#
# Python module Fissures__POA.IfSeismogramDC generated by omniidl

import omniORB
omniORB.updateModule("obspy.fissures.idl.Fissures__POA.IfSeismogramDC")

# ** 1. Stub files contributing to this module
import obspy.fissures.idl.IfConstants_idl
import obspy.fissures.idl.IfDataSetMgr_idl
import obspy.fissures.idl.IfEvent_idl
import obspy.fissures.idl.IfFilter_idl
import obspy.fissures.idl.IfPickMgr_idl
import obspy.fissures.idl.IfPlottable_idl
import obspy.fissures.idl.IfSeismogramDC_idl
import obspy.fissures.idl.IfSeismogramMgr_idl
import obspy.fissures.idl.IfTravelTimeCalculator_idl
import obspy.fissures.idl.master_idl

# ** 2. Sub-modules

# ** 3. End
