# DO NOT EDIT THIS FILE!
#
# Python module Fissures.IfRealTimeCollector generated by omniidl

import omniORB
omniORB.updateModule("idl.Fissures.IfRealTimeCollector")

# ** 1. Stub files contributing to this module
import idl.IfRealTimeCollector_idl

# ** 2. Sub-modules

# ** 3. End
