name: obspydoc
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - decorator
  - lxml
  - matplotlib < 3.11
  - numpy
  - scipy
  - requests  
  # see pypa/setuptools#4480
  - setuptools !=71.0.1
  # see #3258
  - sqlalchemy < 2.0
  # docs
  - cartopy>=0.20
  - pip
  - pybtex
  - m2r2 >= 0.3.2
  - sphinx>=4.2.0
  - sphinx_rtd_theme
  # deps used in tutorial but not working anymore
  #- mlpy
  - doc2dash  # for building docset for dash/zeal
