name: test
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - decorator
  - lxml
  - matplotlib
  - numpy
  - scipy
  - requests
  - setuptools
  # see #3258
  - sqlalchemy < 2.0
  # soft dependencies
  - cartopy
  - geographiclib
  # Pinning version != 3.0.0 for the tests
  # because of doctest failures linked to hardcoded
  # doctest.NORMALIZE_WHITESPACE = 1 (see #3600)
  - pyshp != 3.0.0
  # tests
  - packaging
  - pyproj
  - pytest
  - pytest-cov
  - pytest-json-report >= 1.4
