name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy<1.22
  - scipy
  - matplotlib
  - basemap
  - pip
  - pyproj
  - proj4
  - codecov
  - coverage
  - certifi
  - decorator
  - docopt
  - future
  - jsonschema
  - lxml
  - mock
  - nose
  - requests
  - sqlalchemy
  - cryptography
  - pip:
      - pyimgur
      - -e..
