name: test
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - numpy=1.20
  - scipy=1.7
  - matplotlib=3.3
  - decorator
  - lxml
  - requests
  # see pypa/setuptools#4480
  - setuptools !=71.0.1
  # see #3258
  - sqlalchemy < 2.0
  # soft dependencies
  - cartopy
  - geographiclib
  - pyshp
  # tests
  - packaging
  - pyproj
  - pytest
  - pytest-cov
  - pytest-json-report >= 1.4
