name: test
channels:
  - conda-forge
dependencies:
  # obspy
  - numpy=1.21
  - scipy=1.7
  - matplotlib=3.3
  - decorator
  - lxml
  - requests
  # see pypa/setuptools#4480
  - setuptools !=71.0.1
  # see #3258
  - sqlalchemy < 2.0
  # soft dependencies
  - cartopy < 0.22
  - geographiclib
  # pinning != 3.0.0 - see #3600
  - pyshp != 3.0.0
  # tests
  - packaging
  - pyproj < 3.5
  - pytest
  - pytest-cov
  - pytest-json-report >= 1.4
