name: test
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - decorator
  - lxml
  - matplotlib
  - numpy
  - scipy
  - requests
  - setuptools
  # see #3258
  - sqlalchemy < 2.0
  # soft dependencies
  - cartopy
  - geographiclib
  # pinning <3 - to change once the docset issue is fixed #3600
  - pyshp<3
  # tests
  - packaging
  - pyproj
  - pytest
  - pytest-cov
  - pytest-json-report >= 1.4
