name: test
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - numpy=1.15
  - scipy=1.1
  - matplotlib=3.2
  - decorator
  - lxml
  - requests
  - setuptools
  - sqlalchemy
  # soft dependencies
  - cartopy
  - geographiclib
  - pyshp
  # tests
  - packaging
  - pyproj
  - pytest
  - pytest-cov
  - pytest-json-report >= 1.4
