name: test
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - decorator
  - lxml
  - matplotlib
  - numpy
  - scipy
  - requests
  - setuptools
  - sqlalchemy
  # tests
  - pip
  - pip:
    - pytest-json-report
  - pytest
  - pytest-cov
