name: test
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - numpy=1.20
  - scipy=1.7
  - matplotlib=3.3
  - decorator
  - lxml
  - requests
  - setuptools
  # see #3258
  - sqlalchemy < 2.0
  # soft dependencies
  - cartopy
  - geographiclib
  # pinning != 3.0.0 - see #3600
  - pyshp != 3.0.0
  # tests
  - packaging
  - pyproj
  - pytest
  - pytest-cov
  - pytest-json-report >= 1.4
