# config for codecov, see https://codecov.io/gh/obspy/obspy/settings/yaml

coverage:
  status:

    # set commit status if relative change of whole project coverage
    # exceeds threshold
    project:
      default:
        target: auto
        threshold: 0
        set_pending: yes
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error

    # set commit status, if coverage of diff is below target threshold
    patch:
      default:
        target: 90
        set_pending: yes
        base: auto
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error

    # not exactly sure in what cases this commit status is triggered..
    changes:
      default:
        enabled: no

# no comments in PRs
comment: false
