[build-system]
# Minimum requirements for the build system to execute.
# see PEP518: https://www.python.org/dev/peps/pep-0518/
requires = [
    'setuptools'
    ]
build-backend = "setuptools.build_meta"

# Ignore the pytest sqlite3 db connection errors which
# python3.14 stopped tolerating
[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Exception ignored while finalizing database connection:pytest.PytestUnraisableExceptionWarning",
]