# DO NOT EDIT THIS FILE!
#
# Python module CosTradingRepos__POA generated by omniidl

import omniORB
omniORB.updateModule("CosTradingRepos__POA")

# ** 1. Stub files contributing to this module
import CosTradingRepos_idl

# ** 2. Sub-modules

# ** 3. End
