# DO NOT EDIT THIS FILE!
#
# Python module CosTypedEventComm generated by omniidl

import omniORB
omniORB.updateModule("CosTypedEventComm")

# ** 1. Stub files contributing to this module
import CosTypedEventComm_idl

# ** 2. Sub-modules

# ** 3. End
