# -*- coding: utf-8 -*-
"""
Request hooks shared by ObsPy's HTTP-based clients.

A *request hook* is any callable taking a single :class:`HookRequest` and
returning nothing. It is invoked on every outgoing HTTP request a client
makes, before that request is sent, and may inspect the request and add
headers to it. This is the mechanism ObsPy uses for anything that needs to
attach something to a request based on where that request is going. The
leading example is bearer-token authentication against one or more FDSN
data centers, but a hook is not tied to authentication in any way - it can
add any header, for any reason, based on anything it can read off the
request.

ObsPy's HTTP clients are built on two different stacks:
:class:`obspy.clients.fdsn.client.Client` uses :mod:`urllib.request`, while
:class:`~obspy.clients.base.HTTPClient` (used by
:class:`~obspy.clients.syngine.client.Client` and by the FDSN routing
clients) uses the :mod:`requests` library. The two stacks' request objects
share almost no API - :class:`urllib.request.Request` has ``.host`` and
``.type`` and no ``add_unredirected_header`` equivalent survives into
:class:`requests.PreparedRequest`, for instance - so a hook written against
one would fail on the other. :class:`HookRequest` is a small, stack-neutral
view that normalizes both into the same interface, so that a single hook
works unmodified against every ObsPy HTTP client.

The two backends also differ on *redirects*. On the urllib backend the hook
is invoked again on every request generated by following a redirect, so a
host-aware hook re-resolves what to attach for the new host. On the requests
backend it is not: a hook there is wired in as the ``auth=`` callable on the
initial request, and ``requests`` never re-invokes ``auth=`` while resolving a
redirect (see ``Session.rebuild_auth()``). This means a redirect to a second
host on the requests backend (syngine, the routing clients) goes out with
whatever the hook attached to the *first* request - typically nothing, since
``requests`` itself strips ``Authorization`` on a cross-host redirect - rather
than being re-authenticated for the new host. There is no credential leak
either way; only urllib gets a hook re-run per hop.

A hook is intentionally limited to *reading* the request (URL, host, scheme,
method, headers) and *writing headers*. It cannot rewrite the URL, query
string, body, or method. See :class:`RequestHookHandler` for why.

A hook may be shared across concurrent requests - the routing clients and
the mass downloader both call it from a thread pool - so a hook with mutable
state (e.g. a token cache) must be thread-safe and reentrant.

The same hook object can be handed to as many clients as needed - to a
plain :class:`~obspy.clients.fdsn.client.Client`, to a
:class:`~obspy.clients.fdsn.routing.routing_client.RoutingClient` (which
forwards it to every data center it discovers), or to the
:class:`~obspy.clients.fdsn.mass_downloader.mass_downloader.MassDownloader`.
A host-aware hook such as :class:`BearerTokenHook` looks up the token to use,
if any, from the host the request is actually going to, so a single hook is
enough for a federated query touching many data centers - including ones the
caller never explicitly named.

.. rubric:: Example: a plain function hook

Nothing here requires subclassing anything, or using any of the classes
further down in this module - a hook can be as small as a function:

>>> from obspy.clients.fdsn import Client
>>> def add_project_header(request):
...     request.set_header("X-Project-Id", "my-project")
>>> client = Client("EARTHSCOPE",
...                 request_hook=add_project_header)  # doctest: +SKIP

.. rubric:: Included hooks

For common cases, this module also includes a few ready-made hooks, so
that callers don't have to write their own: :class:`BearerTokenHook` for
bearer-token authentication, :class:`LoggingHook` for logging every
outgoing request (optionally including its headers, with credentials
redacted), and :func:`chain` for combining several hooks into one. None
of these are privileged in any way - each is just a callable satisfying
the same protocol described above, and a hook you write yourself works
everywhere they do.

.. rubric:: Example: BearerTokenHook

>>> from obspy.clients.fdsn import Client, RoutingClient
>>> from obspy.clients.hooks import BearerTokenHook
>>> hook = BearerTokenHook({
...     '*.earthscope.org': 'my-earthscope-token',
...     'geofon.gfz.de': 'my-gfz-token',
... })
>>> client = Client("EARTHSCOPE", request_hook=hook)  # doctest: +SKIP
>>> routed = RoutingClient("eida-routing",
...                        request_hook=hook)  # doctest: +SKIP

A mapping value may also be a callable, for a token that needs
refreshing rather than a fixed string - see the next example.

.. rubric:: Example: delegating to an authentication SDK

A mapping value may be a callable rather than a literal token string -
the way to plug in an external SDK that manages login state and token
refresh, e.g. ``earthscope-sdk``:

.. code-block:: python

    import threading

    from earthscope_sdk import EarthScopeClient
    from obspy.clients.fdsn import RoutingClient
    from obspy.clients.hooks import BearerTokenHook

    esc = EarthScopeClient()
    lock = threading.Lock()

    def earthscope_token(request):
        # Serialize refreshes: this hook is called concurrently by the
        # routing client and the mass downloader, and the SDK does not
        # lock its own refresh path.
        with lock:
            esc.ctx.auth_flow.refresh_if_necessary()
            return esc.ctx.auth_flow.access_token

    hook = BearerTokenHook({
        '*.earthscope.org': earthscope_token,
        'geofon.gfz.de': 'my-static-gfz-token',
    })
    client = RoutingClient("earthscope-federator", request_hook=hook)

``earthscope_token`` is only ever called for a request to a host it is
mapped to, so it never has to check for itself, and its token cannot
reach another data center. It is consulted afresh on every such request -
``refresh_if_necessary()`` is cheap once cached - and a raise (e.g. not
logged in) surfaces as :exc:`RequestHookError` rather than silently
downloading only the open data. Static and dynamic entries mix freely in
one mapping, as above.

:copyright:
    The ObsPy Development Team (devs@obspy.org)
:license:
    GNU Lesser General Public License, Version 3
    (https://www.gnu.org/copyleft/lesser.html)
"""
from abc import ABCMeta, abstractmethod
import logging
import re
import urllib.request as urllib_request
from urllib.parse import urlparse

from obspy.clients.base import ClientException


class RequestHookError(ClientException):
    """
    Raised when a request hook raises while processing a request.

    Never swallowed by the generic exception handling ObsPy's clients apply
    to every other kind of request failure - see the module docstring above
    and, for where each client re-raises it rather than downgrading it,
    :func:`~obspy.clients.fdsn.client.download_url`,
    :func:`~obspy.clients.fdsn.routing.routing_client._try_download_bulk`
    and
    :meth:`~obspy.clients.fdsn.mass_downloader.download_helpers.ClientDownloadHelper.get_availability`.
    """
    pass


class HookRequest(metaclass=ABCMeta):
    """
    Stack-neutral, read-mostly view of an outgoing HTTP request.

    This is what a request hook actually receives - never the native
    :class:`urllib.request.Request` or :class:`requests.PreparedRequest`
    object directly, so that the same hook works against both.

    Header name capitalization is not normalized between the two backend
    implementations: urllib normalizes a name via ``str.capitalize()`` (so
    ``"X-Api-Key"`` becomes ``"X-api-key"``), while requests preserves it as
    given. Both are valid HTTP - header names are case-insensitive - but a
    hook that reads back its own header by name should compare names
    case-insensitively rather than assume a particular capitalization.
    """

    @property
    @abstractmethod
    def url(self):
        """The full URL the request is being sent to."""

    @property
    @abstractmethod
    def host(self):
        """The host (netloc) the request is being sent to."""

    @property
    @abstractmethod
    def scheme(self):
        """The URL scheme, e.g. ``"https"`` or ``"http"``."""

    @property
    @abstractmethod
    def method(self):
        """The HTTP method, e.g. ``"GET"`` or ``"POST"``."""

    @property
    @abstractmethod
    def headers(self):
        """
        A read-only mapping of the headers currently set on the request.

        Includes headers set by either :meth:`set_header` or
        :meth:`set_secret_header`, including by an earlier hook in a
        :func:`chain`, on both backends. The one caveat is name
        capitalization, not visibility - see the class docstring.

        Because this includes anything set via :meth:`set_secret_header`,
        a hook that logs, prints, or otherwise exports these values must
        redact the credential-bearing ones itself - see
        :attr:`LoggingHook.DEFAULT_REDACT` for the header names ObsPy's own
        included hook treats that way.
        """

    @abstractmethod
    def set_header(self, name, value):
        """
        Set a header on the outgoing request.

        Unlike :meth:`set_secret_header`, a header set this way is copied
        onto any redirect target the client may follow.

        :type name: str
        :param name: Header name.
        :type value: str
        :param value: Header value.
        """

    @abstractmethod
    def set_secret_header(self, name, value):
        """
        Set a header that must not be copied onto a cross-host redirect.

        This is the redirect-safe way to attach a credential (a bearer
        token, an API key, ...) to a request. Use it rather than
        :meth:`set_header` for anything sensitive.

        The two backends implement this differently:

        - On the urllib backend, the header is added with
          :meth:`Request.add_unredirected_header()
          <urllib.request.Request.add_unredirected_header>`. It is still
          sent with the request, but it is not part of the header dict
          ObsPy's redirect handler copies onto a redirect target, so it
          cannot follow a redirect to a different host.
        - On the requests backend, this is a plain header. It is still
          redirect-safe there because ``requests`` itself strips the
          ``Authorization`` header on a cross-host redirect
          (``Session.rebuild_auth()``).

        In other words: for the ``Authorization`` header specifically,
        ``set_secret_header`` is redirect-safe on both backends. For any
        other header name, only the urllib backend is guaranteed to drop it
        on a cross-host redirect.

        :type name: str
        :param name: Header name.
        :type value: str
        :param value: Header value.
        """


class _UrllibHookRequest(HookRequest):
    """
    :class:`HookRequest` view of a :class:`urllib.request.Request`.
    """
    def __init__(self, request):
        self._request = request

    @property
    def url(self):
        return self._request.full_url

    @property
    def host(self):
        return self._request.host

    @property
    def scheme(self):
        return self._request.type

    @property
    def method(self):
        return self._request.get_method()

    @property
    def headers(self):
        return dict(self._request.header_items())

    def set_header(self, name, value):
        self._request.add_header(name, value)

    def set_secret_header(self, name, value):
        self._request.add_unredirected_header(name, value)


class _RequestsHookRequest(HookRequest):
    """
    :class:`HookRequest` view of a :class:`requests.PreparedRequest`.
    """
    def __init__(self, request):
        self._request = request
        self._parsed = urlparse(request.url)

    @property
    def url(self):
        return self._request.url

    @property
    def host(self):
        return self._parsed.netloc

    @property
    def scheme(self):
        return self._parsed.scheme

    @property
    def method(self):
        return self._request.method

    @property
    def headers(self):
        return dict(self._request.headers)

    def set_header(self, name, value):
        self._request.headers[name] = value

    def set_secret_header(self, name, value):
        # requests has no unredirected-header concept; a plain header is
        # nonetheless redirect-safe for "Authorization" specifically, since
        # Session.rebuild_auth() strips that header on a cross-host
        # redirect. See the set_secret_header() docstring on HookRequest.
        self._request.headers[name] = value


def _call_hook(hook, hook_request, url_for_errors):
    """
    Invoke ``hook`` on ``hook_request``, wrapping any exception it raises.

    Shared by both backends so a broken hook fails the same way regardless
    of which client is using it. ``hook`` may itself be a :func:`chain` of
    hooks, each already run through this function - in that case the
    wrapping here is a no-op, since :exc:`RequestHookError` is re-raised
    rather than wrapped again, so the error keeps naming the hook that
    actually failed instead of the wrapping ``chain``.
    """
    try:
        hook(hook_request)
    except RequestHookError:
        raise
    except Exception as e:
        raise RequestHookError(
            "Request hook %r failed on '%s': %s" % (
                hook, url_for_errors, e)) from e


class RequestHookHandler(urllib_request.BaseHandler):
    """
    urllib handler that runs a request hook on every outgoing request.

    Add an instance of this to an :class:`~urllib.request.OpenerDirector`
    (e.g. via :func:`urllib.request.build_opener`) to have ``hook`` invoked
    on every request that opener sends, including ones generated by
    following a redirect.
    """
    # urllib's own do_request_() (which fills in the Host and
    # Content-Length headers, among others) runs at handler_order 500.
    # Running after it, at 900, means the hook always sees a fully
    # populated request - this is also why hooks may not rewrite the URL:
    # do_request_() would have already computed Host/Content-Length for the
    # *original* URL, and a hook running afterwards has no chance to fix
    # them up again.
    handler_order = 900

    def __init__(self, hook):
        self._hook = hook

    def http_request(self, req):
        _call_hook(self._hook, _UrllibHookRequest(req), req.full_url)
        return req

    https_request = http_request


def _compile_host_pattern(pattern):
    """
    Compile a host pattern into a regex matching a whole netloc.

    Only ``*`` (any run of characters, dots included) and ``?`` (any
    single character) are metacharacters; every other character is
    literal. This is deliberately *not* :func:`fnmatch.fnmatch`, which
    would additionally read ``[`` as a character class - an IPv6 netloc
    key such as ``"[fe80::1]:8080"`` would then match a host of ``"f"``,
    and hand it that host's token.

    The pattern is expected to be lowercased already, as is whatever it
    is matched against, so the regex itself is case-sensitive and
    behaves the same on every platform (unlike :func:`fnmatch.fnmatch`).
    """
    return re.compile("".join(
        ".*" if char == "*" else "." if char == "?" else re.escape(char)
        for char in pattern))


class BearerTokenHook(object):
    """
    Request hook attaching an ``Authorization: Bearer <token>`` header.

    This is a convenience implementation of the request-hook protocol
    described in the module docstring, not a special case of it - it
    exists so that callers authenticating with a bearer token don't have
    to write their own hook calling :meth:`~HookRequest.set_secret_header`.

    Scoped per host, so that a single instance can be shared across a
    federated query touching several data centers, each with its own
    token - and so that a token for one data center is never sent to
    another.

    :type tokens: dict or callable
    :param tokens: Either a mapping of host (netloc) to the token to use
        for that host, or a single callable applied to every host.

        A mapping value is either a literal token string or a *token
        provider* - a callable ``f(request) -> token or None`` taking the
        :class:`HookRequest` and returning the token to use for this
        particular request, or ``None`` to leave it unauthenticated. A
        provider is what to use for a token that must be refreshed,
        fetched lazily, or resolved some other dynamic way; a literal
        string is the common static case. The two mix freely in one
        mapping. Only the provider mapped to the host the request is
        actually going to is ever invoked - a provider for one data
        center is never consulted for a request to another, let alone its
        token attached.

        Passing a single callable ``f(request) -> token or None`` in
        place of the whole mapping applies it to every host, with no
        allowlist. Use that form when the choice of token needs logic a
        glob key cannot express; use the mapping form - whose keys double
        as the allowlist - otherwise.

        A callable in either position is a *token resolver*, not a
        request hook itself: it returns a token string (or ``None``)
        rather than mutating the request. ``BearerTokenHook`` is the
        hook; it is what calls :meth:`~HookRequest.set_secret_header`
        with the token the resolver returns, together with the header
        name, the ``Bearer `` prefix, the ``require_https`` guard, and
        the fail-open behaviour described below. Such a callable may be
        invoked concurrently from several threads (see the module
        docstring) and must handle that itself. It is consulted afresh
        on every request that could carry its token - never cached
        between them, which is what makes refresh work - and is not
        consulted at all for a request suppressed by ``require_https``,
        so a plain-http request never triggers a token refresh. If it
        raises, the exception is wrapped in :exc:`RequestHookError` naming
        this hook and the URL, never swallowed. See the module docstring
        for a worked example delegating to an external authentication SDK.

        Mapping keys are netlocs, matched case-insensitively, and are
        either exact - including an explicit port if the URL carries one,
        such as ``"example.com:8080"`` - or a glob pattern such as
        ``"*.earthscope.org"``. In a pattern, ``*`` matches any run of
        characters (dots included) and ``?`` any single one; every other
        character, ``[`` included, is literal, so an IPv6 netloc key such
        as ``"[fe80::1]:8080"`` means exactly itself rather than being
        read as a character class the way :func:`fnmatch.fnmatch` would.

        A pattern is matched against the whole netloc, so
        ``"*.earthscope.org"`` covers ``service.earthscope.org`` and
        ``a.b.earthscope.org``, but neither the bare ``earthscope.org``
        (there is no leading dot for the ``*`` to match) nor
        ``service.earthscope.org:8080`` (the port is part of the netloc).
        Add the extra key, or write ``"*.earthscope.org:*"``, to cover
        those too.

        An exact key always wins over a pattern, and among matching
        patterns the longest wins - ``"*.eu.earthscope.org"`` beats
        ``"*.earthscope.org"`` - so which token a host gets never depends
        on the order the mapping was written in.

        A key is a plain glob, not a domain-aware matcher:
        ``"*earthscope.org"``, with no dot after the ``*``, also matches
        ``evilearthscope.org``. Keep the dot.

        A pattern never matches a netloc that carries userinfo (a
        ``"user:pw@host"`` prefix, which both backends pass through as
        part of the netloc unchanged) - otherwise a pattern ending in
        ``*``, such as ``"*.earthscope.org:*"``, could be satisfied by a
        URL like ``https://a.earthscope.org:x@evil.com/`` and hand this
        key's token to ``evil.com``. Only an exact key, naming that
        netloc outright, can match one.

        A host that is not present in the mapping (or for which a
        callable returns ``None``) is left alone - the request goes out
        unauthenticated rather than raising. This "fail open" behaviour is
        deliberate: most FDSN data centers do not require authentication,
        and a federated query should not break against those just because
        this hook does not have a token for them.
    :type require_https: bool
    :param require_https: If ``True`` (the default), never attach the
        token to a plain HTTP request, to avoid sending it in the clear.
    """
    def __init__(self, tokens, require_https=True):
        if callable(tokens):
            self._resolve = tokens
            # Only a name, never the object's repr - a callable holding a
            # token could put it in its own repr, and this ends up in
            # error messages and tracebacks. See __repr__.
            self._description = getattr(
                tokens, "__name__", type(tokens).__name__)
        else:
            _tokens = {host.lower(): token for host, token in tokens.items()}
            self._description = "hosts=%r" % (sorted(_tokens),)
            # Compile the glob keys once, here, rather than on every
            # request - and sort them longest-first so that a more
            # specific pattern wins over a less specific one, with ties
            # broken lexicographically. Both make the resolution below
            # independent of the order the caller wrote the mapping in.
            # Nothing mutates this afterwards, which is what makes the
            # hook safe to share across the thread pools the routing
            # clients and the mass downloader call it from.
            _patterns = tuple(
                (_compile_host_pattern(key), key)
                for key in sorted(
                    (key for key in _tokens if "*" in key or "?" in key),
                    key=lambda key: (-len(key), key)))

            def _resolve(request):
                # An exact netloc key wins over any pattern - and trying
                # it first is also what keeps a literal key that a glob
                # would misread (an IPv6 netloc, say) working.
                #
                # A mapping value is either a literal token or a token
                # provider with the same signature as the whole-mapping
                # resolver form. Only the provider mapped to the host the
                # request is actually going to is ever invoked.
                host = request.host.lower()
                try:
                    token = _tokens[host]
                except KeyError:
                    token = None
                    # A netloc may carry userinfo ("user:pw@host"), which
                    # both backends hand through unsplit as part of
                    # .host/.netloc. A pattern must not be allowed to
                    # match across that "@" - otherwise a URL such as
                    # "https://a.earthscope.org:x@evil.com/" would
                    # satisfy "*.earthscope.org:*" and hand this host's
                    # token to evil.com. An exact key is unaffected: it
                    # would have to name that exact netloc to match at
                    # all, which is the caller's own explicit choice.
                    if "@" not in host:
                        for regex, key in _patterns:
                            if regex.fullmatch(host):
                                token = _tokens[key]
                                break
                if callable(token):
                    token = token(request)
                return token

            self._resolve = _resolve
        self._require_https = require_https

    def __repr__(self):
        return "%s(%s)" % (type(self).__name__, self._description)

    def __call__(self, request):
        if self._require_https and request.scheme != "https":
            return
        token = self._resolve(request)
        if token is None:
            return
        request.set_secret_header("Authorization", "Bearer " + token)


class LoggingHook(object):
    """
    Request hook that logs every outgoing request. Never mutates a request.

    Like :class:`BearerTokenHook`, this is a convenience implementation of
    the request-hook protocol, not a special case of it - logging every
    outgoing request is common enough to be worth a ready-made hook for,
    but nothing here couldn't be written as a two-line function of your
    own.

    Useful on its own, or composed with :func:`chain` alongside an
    authenticating hook, to get a record of every URL and host a federated
    download actually touched.

    With ``headers=True``, also logs the request's headers - including any
    added by an earlier hook in a :func:`chain`, such as an
    ``Authorization`` header attached by :class:`BearerTokenHook` - which is
    the way to answer "did my auth hook actually attach a token?" without
    writing a throwaway hook of your own. Because :attr:`HookRequest.headers`
    deliberately includes headers set via
    :meth:`~HookRequest.set_secret_header` (see that method's docstring),
    values considered credentials are redacted by default; see ``redact``
    below. Only headers set by a hook *earlier* in the chain are visible, so
    ``chain(LoggingHook(headers=True), BearerTokenHook(...))`` logs the
    request before the token is attached, while the reverse order logs it
    (redacted) afterwards.

    :type logger: :class:`logging.Logger`
    :param logger: Logger to use. Defaults to a logger named
        ``"obspy.clients.hooks"``.
    :type level: int
    :param level: Logging level to log requests at. Defaults to
        :data:`logging.DEBUG`.
    :type headers: bool
    :param headers: If ``True``, also log the request's headers, one per
        line, sorted by name. Defaults to ``False``.
    :type redact: iterable of str or None
    :param redact: Header names (matched case-insensitively) whose values
        are replaced with ``"<redacted>"`` rather than logged as-is. Only
        relevant when ``headers=True``. Defaults to
        :attr:`DEFAULT_REDACT`; pass ``()`` to log every value verbatim -
        not recommended for anything hitting a real data center.
    """
    #: Header names (case-insensitive) redacted by default when
    #: ``headers=True`` - the common carriers of a credential.
    DEFAULT_REDACT = ("authorization", "proxy-authorization", "cookie",
                      "set-cookie", "x-api-key")

    def __init__(self, logger=None, level=logging.DEBUG, headers=False,
                 redact=None):
        self._logger = logger or logging.getLogger("obspy.clients.hooks")
        self._level = level
        self._headers = headers
        self._redact = frozenset(
            name.lower() for name in
            (self.DEFAULT_REDACT if redact is None else redact))

    def __call__(self, request):
        if not self._headers:
            self._logger.log(
                self._level, "%s %s", request.method, request.url)
            return
        # Guard explicitly rather than relying on the logger to no-op on a
        # disabled level - building the header block is not free, and
        # nothing here should touch header values at all when nothing is
        # going to be logged.
        if not self._logger.isEnabledFor(self._level):
            return
        lines = ["%s %s" % (request.method, request.url)]
        for name, value in sorted(request.headers.items()):
            if name.lower() in self._redact:
                value = "<redacted>"
            lines.append("    %s: %s" % (name, value))
        self._logger.log(self._level, "\n".join(lines))


def chain(*hooks):
    """
    Compose several request hooks into a single one.

    Clients accept a single ``request_hook``; use this to combine several,
    e.g. an authenticating hook and a logging hook. Hooks run in the order
    given, each seeing the request as left by the previous one.

    An included hook and a plain function hook compose the same way - the
    ``chain`` below combines both:

    >>> from obspy.clients.hooks import BearerTokenHook, chain
    >>> def add_project_header(request):
    ...     request.set_header("X-Project-Id", "my-project")
    >>> hook = chain(
    ...     BearerTokenHook({'service.earthscope.org': 'token'}),
    ...     add_project_header,
    ... )
    """
    def _chained(request):
        for hook in hooks:
            # Route each hook through _call_hook individually, rather than
            # just calling it directly and letting a raise propagate up to
            # be wrapped by the *caller's* _call_hook - that would report
            # the error as coming from this "hook" (i.e. _chained itself)
            # rather than from whichever hook in the chain actually failed.
            _call_hook(hook, request, request.url)
    return _chained


if __name__ == '__main__':
    import doctest
    doctest.testmod(exclude_empty=True)
