# -*- coding: utf-8 -*-
"""
Request hooks shared by ObsPy's HTTP-based clients.

A *request hook* is a callable that gets to inspect (and add headers to)
every outgoing HTTP request a client makes, before it is sent. It is the
mechanism ObsPy uses for anything that needs to attach something to a
request based on where that request is going, the leading example being
bearer-token authentication against one or more FDSN data centers.

ObsPy's HTTP clients are built on two different stacks:
:class:`obspy.clients.fdsn.client.Client` uses :mod:`urllib.request`, while
:class:`~obspy.clients.base.HTTPClient` (used by
:class:`~obspy.clients.syngine.client.Client` and by the FDSN routing
clients) uses the :mod:`requests` library. The two stacks' request objects
share almost no API - :class:`urllib.request.Request` has ``.host`` and
``.type`` and no ``add_unredirected_header`` equivalent survives into
:class:`requests.PreparedRequest`, for instance - so a hook written against
one would fail on the other. :class:`HookRequest` is a small, stack-neutral
view that normalizes both into the same interface, so that a single hook
works unmodified against every ObsPy HTTP client.

The two backends also differ on *redirects*. On the urllib backend the hook
is invoked again on every request generated by following a redirect, so a
host-aware hook re-resolves what to attach for the new host. On the requests
backend it is not: a hook there is wired in as the ``auth=`` callable on the
initial request, and ``requests`` never re-invokes ``auth=`` while resolving a
redirect (see ``Session.rebuild_auth()``). This means a redirect to a second
host on the requests backend (syngine, the routing clients) goes out with
whatever the hook attached to the *first* request - typically nothing, since
``requests`` itself strips ``Authorization`` on a cross-host redirect - rather
than being re-authenticated for the new host. There is no credential leak
either way; only urllib gets a hook re-run per hop.

A hook is intentionally limited to *reading* the request (URL, host, scheme,
method, headers) and *writing headers*. It cannot rewrite the URL, query
string, body, or method. See :class:`RequestHookHandler` for why.

A hook may be shared across concurrent requests - the routing clients and
the mass downloader both call it from a thread pool - so a hook with mutable
state (e.g. a token cache) must be thread-safe and reentrant.

The same hook object can be handed to as many clients as needed - to a
plain :class:`~obspy.clients.fdsn.client.Client`, to a
:class:`~obspy.clients.fdsn.routing.routing_client.RoutingClient` (which
forwards it to every data center it discovers), or to the
:class:`~obspy.clients.fdsn.mass_downloader.mass_downloader.MassDownloader`.
A host-aware hook such as :class:`BearerTokenHook` looks up the token to use,
if any, from the host the request is actually going to, so a single hook is
enough for a federated query touching many data centers - including ones the
caller never explicitly named.

.. rubric:: Example

>>> from obspy.clients.fdsn import Client, RoutingClient
>>> from obspy.clients.hooks import BearerTokenHook
>>> hook = BearerTokenHook({
...     'service.earthscope.org': 'my-earthscope-token',
...     'geofon.gfz.de': 'my-gfz-token',
... })
>>> client = Client("EARTHSCOPE", request_hook=hook)  # doctest: +SKIP
>>> routed = RoutingClient("eida-routing",
...                        request_hook=hook)  # doctest: +SKIP

:copyright:
    The ObsPy Development Team (devs@obspy.org)
:license:
    GNU Lesser General Public License, Version 3
    (https://www.gnu.org/copyleft/lesser.html)
"""
from abc import ABCMeta, abstractmethod
import logging
import urllib.request as urllib_request
from urllib.parse import urlparse

from obspy.clients.base import RequestHookError


class HookRequest(metaclass=ABCMeta):
    """
    Stack-neutral, read-mostly view of an outgoing HTTP request.

    This is what a request hook actually receives - never the native
    :class:`urllib.request.Request` or :class:`requests.PreparedRequest`
    object directly, so that the same hook works against both.

    Header name capitalization is not normalized between the two backend
    implementations: urllib normalizes a name via ``str.capitalize()`` (so
    ``"X-Api-Key"`` becomes ``"X-api-key"``), while requests preserves it as
    given. Both are valid HTTP - header names are case-insensitive - but a
    hook that reads back its own header by name should compare names
    case-insensitively rather than assume a particular capitalization.
    """

    @property
    @abstractmethod
    def url(self):
        """The full URL the request is being sent to."""

    @property
    @abstractmethod
    def host(self):
        """The host (netloc) the request is being sent to."""

    @property
    @abstractmethod
    def scheme(self):
        """The URL scheme, e.g. ``"https"`` or ``"http"``."""

    @property
    @abstractmethod
    def method(self):
        """The HTTP method, e.g. ``"GET"`` or ``"POST"``."""

    @property
    @abstractmethod
    def headers(self):
        """
        A read-only mapping of the headers currently set on the request.

        Includes headers set by either :meth:`set_header` or
        :meth:`set_secret_header`, including by an earlier hook in a
        :func:`chain`, on both backends. The one caveat is name
        capitalization, not visibility - see the class docstring.
        """

    @abstractmethod
    def set_header(self, name, value):
        """
        Set a header on the outgoing request.

        Unlike :meth:`set_secret_header`, a header set this way is copied
        onto any redirect target the client may follow.

        :type name: str
        :param name: Header name.
        :type value: str
        :param value: Header value.
        """

    @abstractmethod
    def set_secret_header(self, name, value):
        """
        Set a header that must not be copied onto a cross-host redirect.

        This is the redirect-safe way to attach a credential (a bearer
        token, an API key, ...) to a request. Use it rather than
        :meth:`set_header` for anything sensitive.

        The two backends implement this differently:

        - On the urllib backend, the header is added with
          :meth:`Request.add_unredirected_header()
          <urllib.request.Request.add_unredirected_header>`. It is still
          sent with the request, but it is not part of the header dict
          ObsPy's redirect handler copies onto a redirect target, so it
          cannot follow a redirect to a different host.
        - On the requests backend, this is a plain header. It is still
          redirect-safe there because ``requests`` itself strips the
          ``Authorization`` header on a cross-host redirect
          (``Session.rebuild_auth()``).

        In other words: for the ``Authorization`` header specifically,
        ``set_secret_header`` is redirect-safe on both backends. For any
        other header name, only the urllib backend is guaranteed to drop it
        on a cross-host redirect.

        :type name: str
        :param name: Header name.
        :type value: str
        :param value: Header value.
        """


class _UrllibHookRequest(HookRequest):
    """
    :class:`HookRequest` view of a :class:`urllib.request.Request`.
    """
    def __init__(self, request):
        self._request = request

    @property
    def url(self):
        return self._request.full_url

    @property
    def host(self):
        return self._request.host

    @property
    def scheme(self):
        return self._request.type

    @property
    def method(self):
        return self._request.get_method()

    @property
    def headers(self):
        return dict(self._request.header_items())

    def set_header(self, name, value):
        self._request.add_header(name, value)

    def set_secret_header(self, name, value):
        self._request.add_unredirected_header(name, value)


class _RequestsHookRequest(HookRequest):
    """
    :class:`HookRequest` view of a :class:`requests.PreparedRequest`.
    """
    def __init__(self, request):
        self._request = request
        self._parsed = urlparse(request.url)

    @property
    def url(self):
        return self._request.url

    @property
    def host(self):
        return self._parsed.netloc

    @property
    def scheme(self):
        return self._parsed.scheme

    @property
    def method(self):
        return self._request.method

    @property
    def headers(self):
        return dict(self._request.headers)

    def set_header(self, name, value):
        self._request.headers[name] = value

    def set_secret_header(self, name, value):
        # requests has no unredirected-header concept; a plain header is
        # nonetheless redirect-safe for "Authorization" specifically, since
        # Session.rebuild_auth() strips that header on a cross-host
        # redirect. See the set_secret_header() docstring on HookRequest.
        self._request.headers[name] = value


def _call_hook(hook, hook_request, url_for_errors):
    """
    Invoke ``hook`` on ``hook_request``, wrapping any exception it raises.

    Shared by both backends so a broken hook fails the same way regardless
    of which client is using it. ``hook`` may itself be a :func:`chain` of
    hooks, each already run through this function - in that case the
    wrapping here is a no-op, since :exc:`RequestHookError` is re-raised
    rather than wrapped again, so the error keeps naming the hook that
    actually failed instead of the wrapping ``chain``.
    """
    try:
        hook(hook_request)
    except RequestHookError:
        raise
    except Exception as e:
        raise RequestHookError(
            "Request hook %r failed on '%s': %s" % (
                hook, url_for_errors, e)) from e


class RequestHookHandler(urllib_request.BaseHandler):
    """
    urllib handler that runs a request hook on every outgoing request.

    Add an instance of this to an :class:`~urllib.request.OpenerDirector`
    (e.g. via :func:`urllib.request.build_opener`) to have ``hook`` invoked
    on every request that opener sends, including ones generated by
    following a redirect.
    """
    # urllib's own do_request_() (which fills in the Host and
    # Content-Length headers, among others) runs at handler_order 500.
    # Running after it, at 900, means the hook always sees a fully
    # populated request - this is also why hooks may not rewrite the URL:
    # do_request_() would have already computed Host/Content-Length for the
    # *original* URL, and a hook running afterwards has no chance to fix
    # them up again.
    handler_order = 900

    def __init__(self, hook):
        self._hook = hook

    def http_request(self, req):
        _call_hook(self._hook, _UrllibHookRequest(req), req.full_url)
        return req

    https_request = http_request


class BearerTokenHook(object):
    """
    Request hook attaching an ``Authorization: Bearer <token>`` header.

    Scoped per host, so that a single instance can be shared across a
    federated query touching several data centers, each with its own
    token - and so that a token for one data center is never sent to
    another.

    :type tokens: dict or callable
    :param tokens: Either a mapping of host (netloc) to token, or a
        callable ``f(request) -> token or None`` taking a
        :class:`HookRequest` and returning the token to use, or ``None`` if
        this request should not be authenticated. A callable is useful for
        tokens that must be refreshed, fetched lazily, or resolved some
        other dynamic way - note that a callable may be invoked
        concurrently from several threads (see the module docstring) and
        must handle that itself; a mapping is sugar for the common static
        case and is looked up by :attr:`HookRequest.host`.

        The mapping is matched case-insensitively against the request's
        netloc - i.e. including an explicit port if the URL carries one,
        such as ``"example.com:8080"`` - since host names are not
        case-sensitive but this lookup would otherwise be an exact string
        match.

        A host that is not present in the mapping (or for which the
        callable returns ``None``) is left alone - the request goes out
        unauthenticated rather than raising. This "fail open" behaviour is
        deliberate: most FDSN data centers do not require authentication,
        and a federated query should not break against those just because
        this hook does not have a token for them.
    :type require_https: bool
    :param require_https: If ``True`` (the default), never attach the
        token to a plain HTTP request, to avoid sending it in the clear.
    """
    def __init__(self, tokens, require_https=True):
        if callable(tokens):
            self._resolve = tokens
        else:
            _tokens = {host.lower(): token for host, token in tokens.items()}
            self._resolve = lambda request: _tokens.get(
                request.host.lower())
        self._require_https = require_https

    def __call__(self, request):
        if self._require_https and request.scheme != "https":
            return
        token = self._resolve(request)
        if token is None:
            return
        request.set_secret_header("Authorization", "Bearer " + token)


class LoggingHook(object):
    """
    Request hook that logs every outgoing request. Never mutates a request.

    Useful on its own, or composed with :func:`chain` alongside an
    authenticating hook, to get a record of every URL and host a federated
    download actually touched.

    :type logger: :class:`logging.Logger`
    :param logger: Logger to use. Defaults to a logger named
        ``"obspy.clients.hooks"``.
    :type level: int
    :param level: Logging level to log requests at. Defaults to
        :data:`logging.DEBUG`.
    """
    def __init__(self, logger=None, level=logging.DEBUG):
        self._logger = logger or logging.getLogger("obspy.clients.hooks")
        self._level = level

    def __call__(self, request):
        self._logger.log(
            self._level, "%s %s", request.method, request.url)


def chain(*hooks):
    """
    Compose several request hooks into a single one.

    Clients accept a single ``request_hook``; use this to combine several,
    e.g. an authenticating hook and a logging hook. Hooks run in the order
    given, each seeing the request as left by the previous one.

    >>> from obspy.clients.hooks import BearerTokenHook, LoggingHook, chain
    >>> hook = chain(
    ...     BearerTokenHook({'service.earthscope.org': 'token'}),
    ...     LoggingHook(),
    ... )
    """
    def _chained(request):
        for hook in hooks:
            # Route each hook through _call_hook individually, rather than
            # just calling it directly and letting a raise propagate up to
            # be wrapped by the *caller's* _call_hook - that would report
            # the error as coming from this "hook" (i.e. _chained itself)
            # rather than from whichever hook in the chain actually failed.
            _call_hook(hook, request, request.url)
    return _chained


if __name__ == '__main__':
    import doctest
    doctest.testmod(exclude_empty=True)
