# DO NOT EDIT THIS FILE!
#
# Python module CosPersistencePDS_DA generated by omniidl

import omniORB
omniORB.updateModule("CosPersistencePDS_DA")

# ** 1. Stub files contributing to this module
import CosPersistencePDS_DA_idl

# ** 2. Sub-modules

# ** 3. End
