# DO NOT EDIT THIS FILE!
#
# Python module CosTypedEventChannelAdmin__POA generated by omniidl

import omniORB
omniORB.updateModule("CosTypedEventChannelAdmin__POA")

# ** 1. Stub files contributing to this module
import CosTypedEventChannelAdmin_idl

# ** 2. Sub-modules

# ** 3. End
