# Python stubs generated by omniidl from IfTravelTimeCalculator.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "Fissures.idl"
import Fissures_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
# #include "IfService.idl"
import IfService_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
_0_Fissures.IfService = omniORB.openModule("Fissures.IfService")
_0_Fissures__POA.IfService = omniORB.openModule("Fissures__POA.IfService")
# #include "IfNetwork.idl"
import IfNetwork_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
_0_Fissures.IfNetwork = omniORB.openModule("Fissures.IfNetwork")
_0_Fissures__POA.IfNetwork = omniORB.openModule("Fissures__POA.IfNetwork")
# #include "IfTimeSeries.idl"
import IfTimeSeries_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
_0_Fissures.IfTimeSeries = omniORB.openModule("Fissures.IfTimeSeries")
_0_Fissures__POA.IfTimeSeries = omniORB.openModule("Fissures__POA.IfTimeSeries")
# #include "IfParameterMgr.idl"
import IfParameterMgr_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
_0_Fissures.IfParameterMgr = omniORB.openModule("Fissures.IfParameterMgr")
_0_Fissures__POA.IfParameterMgr = omniORB.openModule("Fissures__POA.IfParameterMgr")
# #include "IfSeismogramDC.idl"
import IfSeismogramDC_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
_0_Fissures.IfSeismogramDC = omniORB.openModule("Fissures.IfSeismogramDC")
_0_Fissures__POA.IfSeismogramDC = omniORB.openModule("Fissures__POA.IfSeismogramDC")
# #include "IfSeismogramMgr.idl"
import IfSeismogramMgr_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
_0_Fissures.IfSeismogramMgr = omniORB.openModule("Fissures.IfSeismogramMgr")
_0_Fissures__POA.IfSeismogramMgr = omniORB.openModule("Fissures__POA.IfSeismogramMgr")
# #include "IfDataSetMgr.idl"
import IfDataSetMgr_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
_0_Fissures.IfDataSetMgr = omniORB.openModule("Fissures.IfDataSetMgr")
_0_Fissures__POA.IfDataSetMgr = omniORB.openModule("Fissures__POA.IfDataSetMgr")
# #include "IfPickMgr.idl"
import IfPickMgr_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
_0_Fissures.IfPickMgr = omniORB.openModule("Fissures.IfPickMgr")
_0_Fissures__POA.IfPickMgr = omniORB.openModule("Fissures__POA.IfPickMgr")
# #include "CosEventComm.idl"
import CosEventComm_idl
_0_CosEventComm = omniORB.openModule("CosEventComm")
_0_CosEventComm__POA = omniORB.openModule("CosEventComm__POA")
# #include "CosEventChannelAdmin.idl"
import CosEventChannelAdmin_idl
_0_CosEventChannelAdmin = omniORB.openModule("CosEventChannelAdmin")
_0_CosEventChannelAdmin__POA = omniORB.openModule("CosEventChannelAdmin__POA")
# #include "IfEvent.idl"
import IfEvent_idl
_0_Fissures = omniORB.openModule("Fissures")
_0_Fissures__POA = omniORB.openModule("Fissures__POA")
_0_Fissures.IfEvent = omniORB.openModule("Fissures.IfEvent")
_0_Fissures__POA.IfEvent = omniORB.openModule("Fissures__POA.IfEvent")

#
# Start of module "Fissures"
#
__name__ = "Fissures"
_0_Fissures = omniORB.openModule("Fissures", r"IfTravelTimeCalculator.idl")
_0_Fissures__POA = omniORB.openModule("Fissures__POA", r"IfTravelTimeCalculator.idl")


#
# Start of module "Fissures.IfTravelTimeCalculator"
#
__name__ = "Fissures.IfTravelTimeCalculator"
_0_Fissures.IfTravelTimeCalculator = omniORB.openModule("Fissures.IfTravelTimeCalculator", r"IfTravelTimeCalculator.idl")
_0_Fissures__POA.IfTravelTimeCalculator = omniORB.openModule("Fissures__POA.IfTravelTimeCalculator", r"IfTravelTimeCalculator.idl")

_0_Fissures.IfTravelTimeCalculator.VERSION = "1.0"

# typedef ... PhaseNameSeq
class PhaseNameSeq:
    _NP_RepositoryId = "IDL:iris.edu/Fissures/IfTravelTimeCalculator/PhaseNameSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Fissures.IfTravelTimeCalculator.PhaseNameSeq = PhaseNameSeq
_0_Fissures.IfTravelTimeCalculator._d_PhaseNameSeq  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_Fissures.IfTravelTimeCalculator._ad_PhaseNameSeq = (omniORB.tcInternal.tv_alias, PhaseNameSeq._NP_RepositoryId, "PhaseNameSeq", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_Fissures.IfTravelTimeCalculator._tc_PhaseNameSeq = omniORB.tcInternal.createTypeCode(_0_Fissures.IfTravelTimeCalculator._ad_PhaseNameSeq)
omniORB.registerType(PhaseNameSeq._NP_RepositoryId, _0_Fissures.IfTravelTimeCalculator._ad_PhaseNameSeq, _0_Fissures.IfTravelTimeCalculator._tc_PhaseNameSeq)
del PhaseNameSeq

# typedef ... ModelNameSeq
class ModelNameSeq:
    _NP_RepositoryId = "IDL:iris.edu/Fissures/IfTravelTimeCalculator/ModelNameSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Fissures.IfTravelTimeCalculator.ModelNameSeq = ModelNameSeq
_0_Fissures.IfTravelTimeCalculator._d_ModelNameSeq  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_Fissures.IfTravelTimeCalculator._ad_ModelNameSeq = (omniORB.tcInternal.tv_alias, ModelNameSeq._NP_RepositoryId, "ModelNameSeq", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_Fissures.IfTravelTimeCalculator._tc_ModelNameSeq = omniORB.tcInternal.createTypeCode(_0_Fissures.IfTravelTimeCalculator._ad_ModelNameSeq)
omniORB.registerType(ModelNameSeq._NP_RepositoryId, _0_Fissures.IfTravelTimeCalculator._ad_ModelNameSeq, _0_Fissures.IfTravelTimeCalculator._tc_ModelNameSeq)
del ModelNameSeq

# typedef ... VelocityModelId
class VelocityModelId:
    _NP_RepositoryId = "IDL:iris.edu/Fissures/IfTravelTimeCalculator/VelocityModelId:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Fissures.IfTravelTimeCalculator.VelocityModelId = VelocityModelId
_0_Fissures.IfTravelTimeCalculator._d_VelocityModelId  = (omniORB.tcInternal.tv_string,0)
_0_Fissures.IfTravelTimeCalculator._ad_VelocityModelId = (omniORB.tcInternal.tv_alias, VelocityModelId._NP_RepositoryId, "VelocityModelId", (omniORB.tcInternal.tv_string,0))
_0_Fissures.IfTravelTimeCalculator._tc_VelocityModelId = omniORB.tcInternal.createTypeCode(_0_Fissures.IfTravelTimeCalculator._ad_VelocityModelId)
omniORB.registerType(VelocityModelId._NP_RepositoryId, _0_Fissures.IfTravelTimeCalculator._ad_VelocityModelId, _0_Fissures.IfTravelTimeCalculator._tc_VelocityModelId)
del VelocityModelId

# interface TravelTimeCalculator
_0_Fissures.IfTravelTimeCalculator._d_TravelTimeCalculator = (omniORB.tcInternal.tv_objref, "IDL:iris.edu/Fissures/IfTravelTimeCalculator/TravelTimeCalculator:1.0", "TravelTimeCalculator")
omniORB.typeMapping["IDL:iris.edu/Fissures/IfTravelTimeCalculator/TravelTimeCalculator:1.0"] = _0_Fissures.IfTravelTimeCalculator._d_TravelTimeCalculator
_0_Fissures.IfTravelTimeCalculator.TravelTimeCalculator = omniORB.newEmptyClass()
class TravelTimeCalculator (_0_Fissures.IfService.Service):
    _NP_RepositoryId = _0_Fissures.IfTravelTimeCalculator._d_TravelTimeCalculator[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Fissures.IfTravelTimeCalculator.TravelTimeCalculator = TravelTimeCalculator
_0_Fissures.IfTravelTimeCalculator._tc_TravelTimeCalculator = omniORB.tcInternal.createTypeCode(_0_Fissures.IfTravelTimeCalculator._d_TravelTimeCalculator)
omniORB.registerType(TravelTimeCalculator._NP_RepositoryId, _0_Fissures.IfTravelTimeCalculator._d_TravelTimeCalculator, _0_Fissures.IfTravelTimeCalculator._tc_TravelTimeCalculator)

# TravelTimeCalculator operations and attributes
TravelTimeCalculator._d_calculate_travel_times = ((omniORB.typeMapping["IDL:iris.edu/Fissures/IfService/ConfigurationId:1.0"], omniORB.typeMapping["IDL:iris.edu/Fissures/Location:1.0"], omniORB.typeMapping["IDL:iris.edu/Fissures/Location:1.0"], omniORB.typeMapping["IDL:iris.edu/Fissures/IfTravelTimeCalculator/VelocityModelId:1.0"], omniORB.typeMapping["IDL:iris.edu/Fissures/IfTravelTimeCalculator/PhaseNameSeq:1.0"]), (omniORB.typeMapping["IDL:iris.edu/Fissures/IfEvent/PredictedArrivalSeq:1.0"], omniORB.typeMapping["IDL:iris.edu/Fissures/IfTravelTimeCalculator/PhaseNameSeq:1.0"]), None, None, 1)
TravelTimeCalculator._d_known_phases = ((), (omniORB.typeMapping["IDL:iris.edu/Fissures/IfTravelTimeCalculator/PhaseNameSeq:1.0"], ), None)
TravelTimeCalculator._d_known_models = ((), (omniORB.typeMapping["IDL:iris.edu/Fissures/IfTravelTimeCalculator/ModelNameSeq:1.0"], ), None)

# TravelTimeCalculator object reference
class _objref_TravelTimeCalculator (_0_Fissures.IfService._objref_Service):
    _NP_RepositoryId = TravelTimeCalculator._NP_RepositoryId

    def __init__(self):
        _0_Fissures.IfService._objref_Service.__init__(self)

    def calculate_travel_times(self, *args):
        return _omnipy.invoke(self, "calculate_travel_times", _0_Fissures.IfTravelTimeCalculator.TravelTimeCalculator._d_calculate_travel_times, args)

    def known_phases(self, *args):
        return _omnipy.invoke(self, "known_phases", _0_Fissures.IfTravelTimeCalculator.TravelTimeCalculator._d_known_phases, args)

    def known_models(self, *args):
        return _omnipy.invoke(self, "known_models", _0_Fissures.IfTravelTimeCalculator.TravelTimeCalculator._d_known_models, args)

    __methods__ = ["calculate_travel_times", "known_phases", "known_models"] + _0_Fissures.IfService._objref_Service.__methods__

omniORB.registerObjref(TravelTimeCalculator._NP_RepositoryId, _objref_TravelTimeCalculator)
_0_Fissures.IfTravelTimeCalculator._objref_TravelTimeCalculator = _objref_TravelTimeCalculator
del TravelTimeCalculator, _objref_TravelTimeCalculator

# TravelTimeCalculator skeleton
__name__ = "Fissures__POA.IfTravelTimeCalculator"
class TravelTimeCalculator (_0_Fissures__POA.IfService.Service):
    _NP_RepositoryId = _0_Fissures.IfTravelTimeCalculator.TravelTimeCalculator._NP_RepositoryId


    _omni_op_d = {"calculate_travel_times": _0_Fissures.IfTravelTimeCalculator.TravelTimeCalculator._d_calculate_travel_times, "known_phases": _0_Fissures.IfTravelTimeCalculator.TravelTimeCalculator._d_known_phases, "known_models": _0_Fissures.IfTravelTimeCalculator.TravelTimeCalculator._d_known_models}
    _omni_op_d.update(_0_Fissures__POA.IfService.Service._omni_op_d)

TravelTimeCalculator._omni_skeleton = TravelTimeCalculator
_0_Fissures__POA.IfTravelTimeCalculator.TravelTimeCalculator = TravelTimeCalculator
omniORB.registerSkeleton(TravelTimeCalculator._NP_RepositoryId, TravelTimeCalculator)
del TravelTimeCalculator
__name__ = "Fissures.IfTravelTimeCalculator"

#
# End of module "Fissures.IfTravelTimeCalculator"
#
__name__ = "Fissures"


#
# End of module "Fissures"
#
__name__ = "IfTravelTimeCalculator_idl"

_exported_modules = ( "Fissures", "Fissures.IfTravelTimeCalculator")

# The end.
