# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

package:
  name: obspy
  version: "0.10.1"

source:
  fn: obspy-master.zip
  url: https://pypi.python.org/packages/source/o/obspy/obspy-0.10.1.zip#md5=0d32bcf8e9534d32c91efee84291bad3
  # alternatively we can use a local path, however this fails with
  # shutil.Error: [('/path/to/obspy/misc/docs/source/tutorial/ObsPyTutorial.pdf',
  # '/path/to/miniconda3/conda-bld/work/misc/docs/source/tutorial/ObsPyTutorial.pdf',
  # "[Errno 2] No such file or directory: '/path/to/obspy/misc/docs/source/tutorial/ObsPyTutorial.pdf'")]
  #path: ../../../..

build:
  number: 1
  script: python setup.py install
  # Needed as obspy uses entry points.
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - setuptools
    - argparse # [py26]
    - future
    - numpy
    - mock  # [py2k]
    # SciPy 0.15.0 on OSX and Python 2.6 right now is faulty.
    - scipy ==0.14.0 # [py26 and osx]
    - scipy # [not py26 or not osx]
    - matplotlib
    - lxml
    - sqlalchemy <1.0.0
    - flake8
  run:
    - python
    - setuptools
    - argparse # [py26]
    - future
    - numpy
    - mock  # [py2k]
    # SciPy 0.15.0 on OSX and Python 2.6 right now is faulty.
    - scipy ==0.14.0 # [py26 and osx]
    - scipy # [not py26 or not osx]
    - matplotlib
    - lxml
    - sqlalchemy <1.0.0
    - flake8

test:
  imports:
    - obspy
    - obspy.mseed
  commands:
    - obspy-runtests -r

about:
  home: http://obspy.org
  license: LGPLv3
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."
