{% set version = "1.0.3" %}
{% set sha256 = "7170c7427471f978f7a7b0fe61c2bfb7094c59b3859cd8d5d5bbae6380cc20a5" %}

package:
  name: obspy
  version: {{ version }}

source:
  fn: obspy-{{ version }}.zip
  url: https://pypi.io/packages/source/o/obspy/obspy-1.0.3.zip
  # url: https://github.com/obspy/obspy/files/796697/obspy-1.0.3rc1.zip
  sha256: {{ sha256 }}


build:
  number: 0
  preserve_egg_dir: yes
  detect_binary_files_with_prefix: true
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future
    - numpy
    - scipy
    # the pinning of matplotlib for tests should be removed for later commits
    # after merging obspy/obspy#1616
    - matplotlib 1.5.*
    - lxml
    - sqlalchemy
    - requests
    - decorator
    # there's a packaging problem with icu, see obspy/obspy#1677
    #- icu 58.*
  run:
    - python
    - setuptools
    - future
    - numpy
    - scipy
    # the pinning of matplotlib for tests should be removed for later commits
    # after merging obspy/obspy#1616
    - matplotlib 1.5.*
    - lxml
    - sqlalchemy
    - requests
    - decorator
    - mock  # [py2k]
    # there's a packaging problem with icu, see obspy/obspy#1677
    #- icu 58.*

test:
  requires:
    - flake8
    # the pinning of matplotlib for tests should be removed for later commits
    # after merging obspy/obspy#1616
    - matplotlib 1.5.*
    # there's a packaging problem with icu, see obspy/obspy#1677
    #- icu 58.*
  imports:
    - obspy
    - obspy.io.mseed
  commands:
    - obspy-runtests -r

about:
  home: https://obspy.org
  license: LGPLv3
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."

extra:
  recipe-maintainers:
    - megies
    - krischer
    - barsch
    - QuLogic
    - ThomasLecocq
