package:
  name: obspy
  version: !!str 0.10.0

source:
  fn: taupy.zip
  url: https://github.com/obspy/obspy/archive/taupy.zip
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - obspy = obspy:main
    #
    # Would create an entry point called obspy that calls obspy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - setuptools
    - scipy
    - lxml
    - matplotlib
    - future
    - sqlalchemy
  run:
    - python
    - numpy
    - setuptools
    - scipy
    - lxml
    - matplotlib
    - future
    - sqlalchemy

test:
  # Python imports
  imports:
    - obspy

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.obspy.org
  license: GNU Library or Lesser General Public License (LGPL)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
