# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

package:
  name: obspy
  version: "1.0.0"

source:
  fn: obspy-master.zip
  url: https://pypi.python.org/packages/source/o/obspy/obspy-1.0.0.zip
  md5: 40925691d3b0eaeac39b0513c46cf306
  # alternatively we can use a local path, however this fails with
  # shutil.Error: [('/path/to/obspy/misc/docs/source/tutorial/ObsPyTutorial.pdf',
  # '/path/to/miniconda3/conda-bld/work/misc/docs/source/tutorial/ObsPyTutorial.pdf',
  # "[Errno 2] No such file or directory: '/path/to/obspy/misc/docs/source/tutorial/ObsPyTutorial.pdf'")]
  #path: ../../../..

build:
  number: 0
  # Weird command line options but they somehow make sure that the
  # dependencies are not needed for the building phase.
  script: python setup.py install --single-version-externally-managed --record=/tmp/record.txt
  # Needed as obspy uses entry points.
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - future
    - mock  # [py2k]
    - lxml
    - sqlalchemy
    - flake8
    - decorator
    - requests
    - pyproj
    - nose
test:
  imports:
    - obspy
  commands:
    - obspy-runtests -r --node=conda-builder

about:
  home: https://obspy.org
  license: LGPLv3
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."
