# DO NOT EDIT THIS FILE!
#
# Python module CosQuery generated by omniidl

import omniORB
omniORB.updateModule("CosQuery")

# ** 1. Stub files contributing to this module
import CosQuery_idl

# ** 2. Sub-modules

# ** 3. End
