# DO NOT EDIT THIS FILE!
#
# Python module Fissures.IfTravelTimeCalculator generated by omniidl

import omniORB
omniORB.updateModule("obspy.fissures.idl.Fissures.IfTravelTimeCalculator")

# ** 1. Stub files contributing to this module
import obspy.fissures.idl.IfTravelTimeCalculator_idl
import obspy.fissures.idl.master_idl

# ** 2. Sub-modules

# ** 3. End
