# DO NOT EDIT THIS FILE!
#
# Python module Fissures.IfTravelTimeCalculator generated by omniidl

import omniORB
omniORB.updateModule("idl.Fissures.IfTravelTimeCalculator")

# ** 1. Stub files contributing to this module
import idl.IfTravelTimeCalculator_idl

# ** 2. Sub-modules

# ** 3. End
