# DO NOT EDIT THIS FILE!
#
# Python module CosNotifyFilter__POA generated by omniidl

import omniORB
omniORB.updateModule("CosNotifyFilter__POA")

# ** 1. Stub files contributing to this module
import CosNotifyFilter_idl

# ** 2. Sub-modules

# ** 3. End
