.\" -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OBSPY-MSEED-RECORDANALYZE 1 "October 21, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7) and groff_man(7)
.\" .SH        section heading
.\" .SS        secondary section heading
.\"
.\"
.\" To preview this page as plain text: nroff -man obspy-mseed-recordanalyze
.\"
.SH NAME
obspy-mseed-recordanalyze \- Command-line tool to analyze Mini-SEED record
.SH SYNOPSIS
.B obspy-mseed-recordanalyze
.RI [ options ]
.SH DESCRIPTION
A command-line tool to analyze Mini-SEED records for development purposes. For more help, please run ``obspy-mseed-recordanalyze -h``.
.SH OPTIONS
All options including basic examples are available by calling obspy-mseed-recordanalyze -h
.br
.sp 1
.B \-h
Display extensive help and all other available options
.SH AUTHOR
obspy-mseed-recordanalyze was written by the ObsPy Development Team <devs@obspy.org>. This manual page was written by ObsPy Development Team <devs@obspy.org> for the Debian project (but may be used by others).
