.\" -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OBSPY-PRINT 1 "August 29, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7) and groff_man(7)
.\" .SH        section heading
.\" .SS        secondary section heading
.\"
.\"
.\" To preview this page as plain text: nroff -man obspy-plot
.\"
.SH NAME
obspy-print \- Print stream information for waveform data in local files
.SH SYNOPSIS
.B obspy-print
.RI [ options ] " filename" ...
.SH DESCRIPTION
Script to print information on waveform data contained in local seismogram files. The format is autodetected and can optionally be specified (slightly faster). This manual page was only written as it is necessary for the Debian package.
.SH OPTIONS
All options are available by calling obspy-print --help
.br
.sp 1
.B \-\-help
Display extensive help and all other available options
.SH AUTHOR
obspy-print was written by the ObsPy Development Team <devs@obspy.org>. This manual page was written by ObsPy Development Team <devs@obspy.org> for the Debian project (but may be used by others).
