.\" -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OBSPY-RUNTESTS 1 "June 30, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7) and groff_man(7)
.\" .SH        section heading
.\" .SS        secondary section heading
.\"
.\"
.\" To preview this page as plain text: nroff -man obspy-runtests
.\"
.SH NAME
obspy-runtests \- Run obspy test cases
.SH SYNOPSIS
.B obspy-runtests
.RI [ options ] " test.names" ...
.SH DESCRIPTION
Script to run all test cases, or just specified ones. This manual page was written as it is necessary for the Debian package.
.SH OPTIONS
All options including basic examples are available by calling obspy-runtests --help
.br
.sp 1
.B \-\-help
Display extensive help and all other available options
.SH AUTHOR
obspy-runtests was written by the ObsPy Development Team <devs@obspy.org>. This manual page was written by the ObsPy Development Team <devs@obspy.org> for the Debian project (but may be used by others).
