# DO NOT EDIT THIS FILE!
#
# Python module Fissures__POA generated by omniidl

import omniORB
omniORB.updateModule("idl.Fissures__POA")

# ** 1. Stub files contributing to this module
import idl.Fissures_idl
import idl.IfConstants_idl
import idl.IfDataSetMgr_idl
import idl.IfEvent_idl
import idl.IfFilter_idl
import idl.IfNetwork_idl
import idl.IfParameterMgr_idl
import idl.IfPickMgr_idl
import idl.IfPlottable_idl
import idl.IfRealTimeCollector_idl
import idl.IfSeismogramDC_idl
import idl.IfSeismogramMgr_idl
import idl.IfService_idl
import idl.IfTimeSeries_idl
import idl.IfTravelTimeCalculator_idl

# ** 2. Sub-modules
import IfDataSetMgr
import IfEvent
import IfNetwork
import IfParameterMgr
import IfPickMgr
import IfSeismogramDC
import IfSeismogramMgr
import IfTimeSeries
import IfFilter
import IfService
import IfPlottable
import IfRealTimeCollector
import IfTravelTimeCalculator

# ** 3. End
