# DO NOT EDIT THIS FILE!
#
# Python module CosReference generated by omniidl

import omniORB
omniORB.updateModule("CosReference")

# ** 1. Stub files contributing to this module
import CosReference_idl

# ** 2. Sub-modules

# ** 3. End
