# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests
name: Feature Request
description: Suggest adding something to ObsPy!
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
         Please [search existing issues](https://github.com/obspy/obspy/issues?q=) for relevant feature requests before creating a new feature request.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Briefly describe the problem this feature will solve. (2-4 sentences)
      placeholder: |
        * I'm always frustrated when [...] because [...]
        * I would like it if [...] happened when I [...] because [...]
        * Here is an example image/output/... of what I am asking for [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe a way to accomplish the goals of this feature request.
