# DO NOT EDIT THIS FILE!
#
# Python module CosContainment generated by omniidl

import omniORB
omniORB.updateModule("CosContainment")

# ** 1. Stub files contributing to this module
import CosContainment_idl

# ** 2. Sub-modules

# ** 3. End
