# Python stubs generated by omniidl from ..\..\..\..\..\idl\COS\CosPersistencePDS.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "CosPersistencePID.idl"
import CosPersistencePID_idl
_0_CosPersistencePID = omniORB.openModule("CosPersistencePID")
_0_CosPersistencePID__POA = omniORB.openModule("CosPersistencePID__POA")

#
# Start of module "CosPersistencePDS"
#
__name__ = "CosPersistencePDS"
_0_CosPersistencePDS = omniORB.openModule("CosPersistencePDS", r"..\..\..\..\..\idl\COS\CosPersistencePDS.idl")
_0_CosPersistencePDS__POA = omniORB.openModule("CosPersistencePDS__POA", r"..\..\..\..\..\idl\COS\CosPersistencePDS.idl")


# interface PDS
_0_CosPersistencePDS._d_PDS = (omniORB.tcInternal.tv_objref, "IDL:omg.org/CosPersistencePDS/PDS:1.0", "PDS")
omniORB.typeMapping["IDL:omg.org/CosPersistencePDS/PDS:1.0"] = _0_CosPersistencePDS._d_PDS
_0_CosPersistencePDS.PDS = omniORB.newEmptyClass()
class PDS :
    _NP_RepositoryId = _0_CosPersistencePDS._d_PDS[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_CosPersistencePDS.PDS = PDS
_0_CosPersistencePDS._tc_PDS = omniORB.tcInternal.createTypeCode(_0_CosPersistencePDS._d_PDS)
omniORB.registerType(PDS._NP_RepositoryId, _0_CosPersistencePDS._d_PDS, _0_CosPersistencePDS._tc_PDS)

# PDS operations and attributes
PDS._d_connect = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (omniORB.typeMapping["IDL:omg.org/CosPersistencePDS/PDS:1.0"], ), None)
PDS._d_disconnect = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (), None)
PDS._d_store = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (), None)
PDS._d_restore = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (), None)
PDS._d_delete = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (), None)

# PDS object reference
class _objref_PDS (CORBA.Object):
    _NP_RepositoryId = PDS._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def connect(self, *args):
        return _omnipy.invoke(self, "connect", _0_CosPersistencePDS.PDS._d_connect, args)

    def disconnect(self, *args):
        return _omnipy.invoke(self, "disconnect", _0_CosPersistencePDS.PDS._d_disconnect, args)

    def store(self, *args):
        return _omnipy.invoke(self, "store", _0_CosPersistencePDS.PDS._d_store, args)

    def restore(self, *args):
        return _omnipy.invoke(self, "restore", _0_CosPersistencePDS.PDS._d_restore, args)

    def delete(self, *args):
        return _omnipy.invoke(self, "delete", _0_CosPersistencePDS.PDS._d_delete, args)

    __methods__ = ["connect", "disconnect", "store", "restore", "delete"] + CORBA.Object.__methods__

omniORB.registerObjref(PDS._NP_RepositoryId, _objref_PDS)
_0_CosPersistencePDS._objref_PDS = _objref_PDS
del PDS, _objref_PDS

# PDS skeleton
__name__ = "CosPersistencePDS__POA"
class PDS (PortableServer.Servant):
    _NP_RepositoryId = _0_CosPersistencePDS.PDS._NP_RepositoryId


    _omni_op_d = {"connect": _0_CosPersistencePDS.PDS._d_connect, "disconnect": _0_CosPersistencePDS.PDS._d_disconnect, "store": _0_CosPersistencePDS.PDS._d_store, "restore": _0_CosPersistencePDS.PDS._d_restore, "delete": _0_CosPersistencePDS.PDS._d_delete}

PDS._omni_skeleton = PDS
_0_CosPersistencePDS__POA.PDS = PDS
omniORB.registerSkeleton(PDS._NP_RepositoryId, PDS)
del PDS
__name__ = "CosPersistencePDS"

#
# End of module "CosPersistencePDS"
#
__name__ = "CosPersistencePDS_idl"

_exported_modules = ( "CosPersistencePDS", )

# The end.
