all: unix

unix:
	constructor --platform=linux-64 1.0.3_py27
	constructor --platform=linux-64 1.0.3_py35
	constructor --platform=linux-32 1.0.3_py27
	constructor --platform=linux-32 1.0.3_py35
	constructor --platform=osx-64 1.0.3_py27
	constructor --platform=osx-64 1.0.3_py35
