all: unix win

unix:
	constructor --platform=linux-64 1.0.3_py27
	constructor --platform=linux-64 1.0.3_py35
	constructor --platform=linux-32 1.0.3_py27
	constructor --platform=linux-32 1.0.3_py35
	constructor --platform=osx-64 1.0.3_py27
	constructor --platform=osx-64 1.0.3_py35

win:
	constructor --platform=win-64 1.0.3_py27
	constructor --platform=win-64 1.0.3_py35
	constructor --platform=win-32 1.0.3_py27
	constructor --platform=win-32 1.0.3_py35
