# DO NOT EDIT THIS FILE!
#
# Python module RDITestTypes generated by omniidl

import omniORB
omniORB.updateModule("RDITestTypes")

# ** 1. Stub files contributing to this module
import RDITestTypes_idl

# ** 2. Sub-modules

# ** 3. End
