# DO NOT EDIT THIS FILE!
#
# Python module CosExternalizationReference__POA generated by omniidl

import omniORB
omniORB.updateModule("CosExternalizationReference__POA")

# ** 1. Stub files contributing to this module
import CosExternalizationReference_idl

# ** 2. Sub-modules

# ** 3. End
