# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_processing.ui'
#
# Created: Thu Jul 29 19:21:23 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_BatchDialog(object):
    def setupUi(self, BatchDialog):
        BatchDialog.setObjectName("BatchDialog")
        BatchDialog.resize(1001, 540)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BatchDialog.sizePolicy().hasHeightForWidth())
        BatchDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtGui.QVBoxLayout(BatchDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtGui.QSplitter(BatchDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settingsTreeWidget = QtGui.QTreeWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsTreeWidget.sizePolicy().hasHeightForWidth())
        self.settingsTreeWidget.setSizePolicy(sizePolicy)
        self.settingsTreeWidget.setIndentation(10)
        self.settingsTreeWidget.setRootIsDecorated(True)
        self.settingsTreeWidget.setHeaderHidden(True)
        self.settingsTreeWidget.setColumnCount(2)
        self.settingsTreeWidget.setObjectName("settingsTreeWidget")
        self.settingsTreeWidget.headerItem().setText(0, "1")
        self.settingsTreeWidget.headerItem().setText(1, "2")
        self.verticalLayout_2.addWidget(self.settingsTreeWidget)
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filenameTreeView = FilenameWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameTreeView.sizePolicy().hasHeightForWidth())
        self.filenameTreeView.setSizePolicy(sizePolicy)
        self.filenameTreeView.setObjectName("filenameTreeView")
        self.verticalLayout.addWidget(self.filenameTreeView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filesLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.filesLabel.setFont(font)
        self.filesLabel.setText("")
        self.filesLabel.setObjectName("filesLabel")
        self.horizontalLayout_2.addWidget(self.filesLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.removeItemsButton = QtGui.QPushButton(self.groupBox_2)
        self.removeItemsButton.setObjectName("removeItemsButton")
        self.horizontalLayout_3.addWidget(self.removeItemsButton)
        self.automatchButton = QtGui.QPushButton(self.groupBox_2)
        self.automatchButton.setObjectName("automatchButton")
        self.horizontalLayout_3.addWidget(self.automatchButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.fileDialogButton = QtGui.QPushButton(self.groupBox_2)
        self.fileDialogButton.setObjectName("fileDialogButton")
        self.horizontalLayout_3.addWidget(self.fileDialogButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitCheckBox = QtGui.QCheckBox(BatchDialog)
        self.splitCheckBox.setText("")
        self.splitCheckBox.setChecked(True)
        self.splitCheckBox.setObjectName("splitCheckBox")
        self.horizontalLayout_4.addWidget(self.splitCheckBox)
        self.splitLabel1 = QtGui.QLabel(BatchDialog)
        self.splitLabel1.setObjectName("splitLabel1")
        self.horizontalLayout_4.addWidget(self.splitLabel1)
        self.splitSpinBox = QtGui.QDoubleSpinBox(BatchDialog)
        self.splitSpinBox.setProperty("value", 1.0)
        self.splitSpinBox.setObjectName("splitSpinBox")
        self.horizontalLayout_4.addWidget(self.splitSpinBox)
        self.splitLabel2 = QtGui.QLabel(BatchDialog)
        self.splitLabel2.setObjectName("splitLabel2")
        self.horizontalLayout_4.addWidget(self.splitLabel2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(BatchDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.outputDirLineEdit = QtGui.QLineEdit(BatchDialog)
        self.outputDirLineEdit.setObjectName("outputDirLineEdit")
        self.horizontalLayout.addWidget(self.outputDirLineEdit)
        self.outputDirButton = QtGui.QPushButton(BatchDialog)
        self.outputDirButton.setObjectName("outputDirButton")
        self.horizontalLayout.addWidget(self.outputDirButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancelButton = QtGui.QPushButton(BatchDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.startButton = QtGui.QPushButton(BatchDialog)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(BatchDialog)
        QtCore.QMetaObject.connectSlotsByName(BatchDialog)

    def retranslateUi(self, BatchDialog):
        BatchDialog.setWindowTitle(QtGui.QApplication.translate("BatchDialog", "Batch Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BatchDialog", "Review Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("BatchDialog", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.removeItemsButton.setText(QtGui.QApplication.translate("BatchDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.automatchButton.setText(QtGui.QApplication.translate("BatchDialog", "Automatch Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDialogButton.setText(QtGui.QApplication.translate("BatchDialog", "Add Files", None, QtGui.QApplication.UnicodeUTF8))
        self.splitLabel1.setText(QtGui.QApplication.translate("BatchDialog", "Split every file in", None, QtGui.QApplication.UnicodeUTF8))
        self.splitLabel2.setText(QtGui.QApplication.translate("BatchDialog", "hour windows (recommended for larger files).", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BatchDialog", "Output directory", None, QtGui.QApplication.UnicodeUTF8))
        self.outputDirButton.setText(QtGui.QApplication.translate("BatchDialog", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("BatchDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("BatchDialog", "Start", None, QtGui.QApplication.UnicodeUTF8))

from filenamewidget import FilenameWidget
