# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'htov.ui'
#
# Created: Thu Jul 29 19:21:22 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1140, 759)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.MainSplitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainSplitter.sizePolicy().hasHeightForWidth())
        self.MainSplitter.setSizePolicy(sizePolicy)
        self.MainSplitter.setAutoFillBackground(False)
        self.MainSplitter.setOrientation(QtCore.Qt.Vertical)
        self.MainSplitter.setOpaqueResize(False)
        self.MainSplitter.setObjectName("MainSplitter")
        self.plotTabWidget = QtGui.QTabWidget(self.MainSplitter)
        self.plotTabWidget.setObjectName("plotTabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setMargin(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rawDataPlot = Qt4MplCanvas(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawDataPlot.sizePolicy().hasHeightForWidth())
        self.rawDataPlot.setSizePolicy(sizePolicy)
        self.rawDataPlot.setObjectName("rawDataPlot")
        self.horizontalLayout_5.addWidget(self.rawDataPlot)
        self.plotTabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setMargin(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.editDataPlot = Qt4MplCanvas(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editDataPlot.sizePolicy().hasHeightForWidth())
        self.editDataPlot.setSizePolicy(sizePolicy)
        self.editDataPlot.setObjectName("editDataPlot")
        self.verticalLayout_7.addWidget(self.editDataPlot)
        self.plotTabWidget.addTab(self.tab_2, "")
        self.hvTab = QtGui.QWidget()
        self.hvTab.setObjectName("hvTab")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.hvTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.hvPlot = Qt4MplCanvas(self.hvTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvPlot.sizePolicy().hasHeightForWidth())
        self.hvPlot.setSizePolicy(sizePolicy)
        self.hvPlot.setObjectName("hvPlot")
        self.verticalLayout_9.addWidget(self.hvPlot)
        self.plotTabWidget.addTab(self.hvTab, "")
        self.menuTabWidget = QtGui.QTabWidget(self.MainSplitter)
        self.menuTabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuTabWidget.sizePolicy().hasHeightForWidth())
        self.menuTabWidget.setSizePolicy(sizePolicy)
        self.menuTabWidget.setObjectName("menuTabWidget")
        self.loadDataTab = QtGui.QWidget()
        self.loadDataTab.setObjectName("loadDataTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.loadDataTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filenameLabel = QtGui.QLabel(self.loadDataTab)
        self.filenameLabel.setEnabled(True)
        self.filenameLabel.setText("")
        self.filenameLabel.setObjectName("filenameLabel")
        self.verticalLayout_2.addWidget(self.filenameLabel)
        self.rawDataTable = QtGui.QTableWidget(self.loadDataTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawDataTable.sizePolicy().hasHeightForWidth())
        self.rawDataTable.setSizePolicy(sizePolicy)
        self.rawDataTable.setAlternatingRowColors(False)
        self.rawDataTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.rawDataTable.setRowCount(0)
        self.rawDataTable.setColumnCount(0)
        self.rawDataTable.setObjectName("rawDataTable")
        self.rawDataTable.setColumnCount(0)
        self.rawDataTable.setRowCount(0)
        self.rawDataTable.horizontalHeader().setCascadingSectionResizes(False)
        self.rawDataTable.horizontalHeader().setStretchLastSection(False)
        self.rawDataTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.rawDataTable)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.loadFileButton = QtGui.QPushButton(self.loadDataTab)
        self.loadFileButton.setObjectName("loadFileButton")
        self.horizontalLayout_4.addWidget(self.loadFileButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.menuTabWidget.addTab(self.loadDataTab, "")
        self.editDataTab = QtGui.QWidget()
        self.editDataTab.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editDataTab.sizePolicy().hasHeightForWidth())
        self.editDataTab.setSizePolicy(sizePolicy)
        self.editDataTab.setObjectName("editDataTab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.editDataTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(self.editDataTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.starttimeLabel = QtGui.QLabel(self.groupBox)
        self.starttimeLabel.setEnabled(True)
        self.starttimeLabel.setObjectName("starttimeLabel")
        self.horizontalLayout_9.addWidget(self.starttimeLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.starttimeEdit = QtGui.QDateTimeEdit(self.groupBox)
        self.starttimeEdit.setEnabled(True)
        self.starttimeEdit.setCalendarPopup(True)
        self.starttimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.starttimeEdit.setObjectName("starttimeEdit")
        self.horizontalLayout_9.addWidget(self.starttimeEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.endtimeLabel = QtGui.QLabel(self.groupBox)
        self.endtimeLabel.setEnabled(True)
        self.endtimeLabel.setObjectName("endtimeLabel")
        self.horizontalLayout_10.addWidget(self.endtimeLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.endtimeEdit = QtGui.QDateTimeEdit(self.groupBox)
        self.endtimeEdit.setEnabled(True)
        self.endtimeEdit.setCalendarPopup(True)
        self.endtimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.endtimeEdit.setObjectName("endtimeEdit")
        self.horizontalLayout_10.addWidget(self.endtimeEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.editDataTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.highpassSlider = QtGui.QSlider(self.groupBox_2)
        self.highpassSlider.setEnabled(True)
        self.highpassSlider.setOrientation(QtCore.Qt.Horizontal)
        self.highpassSlider.setObjectName("highpassSlider")
        self.horizontalLayout_8.addWidget(self.highpassSlider)
        self.highpassSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.highpassSpinBox.setDecimals(3)
        self.highpassSpinBox.setObjectName("highpassSpinBox")
        self.horizontalLayout_8.addWidget(self.highpassSpinBox)
        self.highpassLabel = QtGui.QLabel(self.groupBox_2)
        self.highpassLabel.setEnabled(False)
        self.highpassLabel.setObjectName("highpassLabel")
        self.horizontalLayout_8.addWidget(self.highpassLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.lowpassSlider = QtGui.QSlider(self.groupBox_2)
        self.lowpassSlider.setEnabled(True)
        self.lowpassSlider.setProperty("value", 99)
        self.lowpassSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lowpassSlider.setObjectName("lowpassSlider")
        self.horizontalLayout_7.addWidget(self.lowpassSlider)
        self.lowpassSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.lowpassSpinBox.setDecimals(3)
        self.lowpassSpinBox.setMaximum(100.0)
        self.lowpassSpinBox.setProperty("value", 100.0)
        self.lowpassSpinBox.setObjectName("lowpassSpinBox")
        self.horizontalLayout_7.addWidget(self.lowpassSpinBox)
        self.lowpassLabel = QtGui.QLabel(self.groupBox_2)
        self.lowpassLabel.setEnabled(False)
        self.lowpassLabel.setObjectName("lowpassLabel")
        self.horizontalLayout_7.addWidget(self.lowpassLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cornersLabel = QtGui.QLabel(self.groupBox_2)
        self.cornersLabel.setEnabled(True)
        self.cornersLabel.setObjectName("cornersLabel")
        self.horizontalLayout_6.addWidget(self.cornersLabel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.cornersSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.cornersSpinBox.setMaximum(8)
        self.cornersSpinBox.setProperty("value", 4)
        self.cornersSpinBox.setObjectName("cornersSpinBox")
        self.horizontalLayout_6.addWidget(self.cornersSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.zerophaseCheckbox = QtGui.QCheckBox(self.groupBox_2)
        self.zerophaseCheckbox.setEnabled(True)
        self.zerophaseCheckbox.setChecked(False)
        self.zerophaseCheckbox.setAutoRepeat(True)
        self.zerophaseCheckbox.setObjectName("zerophaseCheckbox")
        self.verticalLayout_3.addWidget(self.zerophaseCheckbox)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.editDataTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.resampleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.resampleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resampleSpinBox.setDecimals(3)
        self.resampleSpinBox.setMinimum(0.0)
        self.resampleSpinBox.setMaximum(1000.0)
        self.resampleSpinBox.setProperty("value", 200.0)
        self.resampleSpinBox.setObjectName("resampleSpinBox")
        self.horizontalLayout_12.addWidget(self.resampleSpinBox)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.saveEditedDataButton = QtGui.QPushButton(self.editDataTab)
        self.saveEditedDataButton.setEnabled(False)
        self.saveEditedDataButton.setObjectName("saveEditedDataButton")
        self.horizontalLayout_11.addWidget(self.saveEditedDataButton)
        self.editDataButton = QtGui.QPushButton(self.editDataTab)
        self.editDataButton.setObjectName("editDataButton")
        self.horizontalLayout_11.addWidget(self.editDataButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.menuTabWidget.addTab(self.editDataTab, "")
        self.findNoiseTab = QtGui.QWidget()
        self.findNoiseTab.setObjectName("findNoiseTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.findNoiseTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox_5 = QtGui.QGroupBox(self.findNoiseTab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.zDetectorSpinBox = QtGui.QSpinBox(self.groupBox_5)
        self.zDetectorSpinBox.setMinimum(10)
        self.zDetectorSpinBox.setMaximum(99999)
        self.zDetectorSpinBox.setProperty("value", 40)
        self.zDetectorSpinBox.setObjectName("zDetectorSpinBox")
        self.horizontalLayout_15.addWidget(self.zDetectorSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_17.addWidget(self.label_8)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.thresholdSpinBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.thresholdSpinBox.setProperty("value", 99.0)
        self.thresholdSpinBox.setObjectName("thresholdSpinBox")
        self.horizontalLayout_17.addWidget(self.thresholdSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_13.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.findNoiseTab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.windowLengthSpinBox = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.windowLengthSpinBox.setMinimum(1.0)
        self.windowLengthSpinBox.setMaximum(9999.0)
        self.windowLengthSpinBox.setProperty("value", 25.0)
        self.windowLengthSpinBox.setObjectName("windowLengthSpinBox")
        self.horizontalLayout_14.addWidget(self.windowLengthSpinBox)
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13.addWidget(self.groupBox_6)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.findNoiseButton = QtGui.QPushButton(self.findNoiseTab)
        self.findNoiseButton.setObjectName("findNoiseButton")
        self.horizontalLayout_16.addWidget(self.findNoiseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.menuTabWidget.addTab(self.findNoiseTab, "")
        self.htovTab = QtGui.QWidget()
        self.htovTab.setObjectName("htovTab")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.htovTab)
        self.horizontalLayout_3.setSpacing(-1)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtGui.QGroupBox(self.htovTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_13.setSpacing(-1)
        self.verticalLayout_13.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_23.addWidget(self.label_14)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem10)
        self.spectraMethodComboBox = QtGui.QComboBox(self.groupBox_4)
        self.spectraMethodComboBox.setObjectName("spectraMethodComboBox")
        self.spectraMethodComboBox.addItem("")
        self.spectraMethodComboBox.addItem("")
        self.spectraMethodComboBox.addItem("")
        self.horizontalLayout_23.addWidget(self.spectraMethodComboBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.line_2 = QtGui.QFrame(self.groupBox_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_13.addWidget(self.line_2)
        self.spectraMethodStack = QtGui.QStackedWidget(self.groupBox_4)
        self.spectraMethodStack.setObjectName("spectraMethodStack")
        self.multitaperPage = QtGui.QWidget()
        self.multitaperPage.setObjectName("multitaperPage")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.multitaperPage)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_17 = QtGui.QLabel(self.multitaperPage)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_24.addWidget(self.label_17)
        self.timeBandwidthSpinBox = QtGui.QDoubleSpinBox(self.multitaperPage)
        self.timeBandwidthSpinBox.setDecimals(1)
        self.timeBandwidthSpinBox.setMinimum(0.5)
        self.timeBandwidthSpinBox.setMaximum(20.0)
        self.timeBandwidthSpinBox.setSingleStep(0.1)
        self.timeBandwidthSpinBox.setProperty("value", 4.0)
        self.timeBandwidthSpinBox.setObjectName("timeBandwidthSpinBox")
        self.horizontalLayout_24.addWidget(self.timeBandwidthSpinBox)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem11)
        self.label_19 = QtGui.QLabel(self.multitaperPage)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_24.addWidget(self.label_19)
        self.numberOfTapersComboBox = QtGui.QComboBox(self.multitaperPage)
        self.numberOfTapersComboBox.setObjectName("numberOfTapersComboBox")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.numberOfTapersComboBox.addItem("")
        self.horizontalLayout_24.addWidget(self.numberOfTapersComboBox)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.multitaperPadCheckBox = QtGui.QCheckBox(self.multitaperPage)
        self.multitaperPadCheckBox.setObjectName("multitaperPadCheckBox")
        self.horizontalLayout_25.addWidget(self.multitaperPadCheckBox)
        self.nfftLabel = QtGui.QLabel(self.multitaperPage)
        self.nfftLabel.setEnabled(False)
        self.nfftLabel.setObjectName("nfftLabel")
        self.horizontalLayout_25.addWidget(self.nfftLabel)
        self.nfftSpinBox = QtGui.QSpinBox(self.multitaperPage)
        self.nfftSpinBox.setEnabled(False)
        self.nfftSpinBox.setMaximum(9999999)
        self.nfftSpinBox.setObjectName("nfftSpinBox")
        self.horizontalLayout_25.addWidget(self.nfftSpinBox)
        self.line_3 = QtGui.QFrame(self.multitaperPage)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_25.addWidget(self.line_3)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem12)
        self.quadraticCheckBox = QtGui.QCheckBox(self.multitaperPage)
        self.quadraticCheckBox.setObjectName("quadraticCheckBox")
        self.horizontalLayout_25.addWidget(self.quadraticCheckBox)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem13)
        self.adaptiveCheckBox = QtGui.QCheckBox(self.multitaperPage)
        self.adaptiveCheckBox.setChecked(True)
        self.adaptiveCheckBox.setObjectName("adaptiveCheckBox")
        self.horizontalLayout_25.addWidget(self.adaptiveCheckBox)
        self.verticalLayout_14.addLayout(self.horizontalLayout_25)
        self.spectraMethodStack.addWidget(self.multitaperPage)
        self.sineMultitaperPage = QtGui.QWidget()
        self.sineMultitaperPage.setObjectName("sineMultitaperPage")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.sineMultitaperPage)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_20 = QtGui.QLabel(self.sineMultitaperPage)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_28.addWidget(self.label_20)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem14)
        self.sinePSDTapersSpinBox = QtGui.QSpinBox(self.sineMultitaperPage)
        self.sinePSDTapersSpinBox.setObjectName("sinePSDTapersSpinBox")
        self.horizontalLayout_28.addWidget(self.sinePSDTapersSpinBox)
        self.line_6 = QtGui.QFrame(self.sineMultitaperPage)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_28.addWidget(self.line_6)
        self.label_18 = QtGui.QLabel(self.sineMultitaperPage)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_28.addWidget(self.label_18)
        self.line_5 = QtGui.QFrame(self.sineMultitaperPage)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_28.addWidget(self.line_5)
        self.verticalLayout_15.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_21 = QtGui.QLabel(self.sineMultitaperPage)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_29.addWidget(self.label_21)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem15)
        self.sinePSDIterationsSpinBox = QtGui.QSpinBox(self.sineMultitaperPage)
        self.sinePSDIterationsSpinBox.setMinimum(2)
        self.sinePSDIterationsSpinBox.setProperty("value", 2)
        self.sinePSDIterationsSpinBox.setObjectName("sinePSDIterationsSpinBox")
        self.horizontalLayout_29.addWidget(self.sinePSDIterationsSpinBox)
        self.line_4 = QtGui.QFrame(self.sineMultitaperPage)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_29.addWidget(self.line_4)
        self.label_22 = QtGui.QLabel(self.sineMultitaperPage)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_29.addWidget(self.label_22)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem16)
        self.sinePSDSmoothingSpinBox = QtGui.QDoubleSpinBox(self.sineMultitaperPage)
        self.sinePSDSmoothingSpinBox.setMaximum(99.0)
        self.sinePSDSmoothingSpinBox.setProperty("value", 1.0)
        self.sinePSDSmoothingSpinBox.setObjectName("sinePSDSmoothingSpinBox")
        self.horizontalLayout_29.addWidget(self.sinePSDSmoothingSpinBox)
        self.verticalLayout_15.addLayout(self.horizontalLayout_29)
        self.spectraMethodStack.addWidget(self.sineMultitaperPage)
        self.singleTaperPage = QtGui.QWidget()
        self.singleTaperPage.setObjectName("singleTaperPage")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.singleTaperPage)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_24 = QtGui.QLabel(self.singleTaperPage)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_32.addWidget(self.label_24)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem17)
        self.singleTaperComboBox = QtGui.QComboBox(self.singleTaperPage)
        self.singleTaperComboBox.setObjectName("singleTaperComboBox")
        self.singleTaperComboBox.addItem("")
        self.singleTaperComboBox.addItem("")
        self.singleTaperComboBox.addItem("")
        self.singleTaperComboBox.addItem("")
        self.singleTaperComboBox.addItem("")
        self.singleTaperComboBox.addItem("")
        self.horizontalLayout_32.addWidget(self.singleTaperComboBox)
        self.verticalLayout_16.addLayout(self.horizontalLayout_32)
        self.spectraMethodStack.addWidget(self.singleTaperPage)
        self.verticalLayout_13.addWidget(self.spectraMethodStack)
        self.line = QtGui.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_13.addWidget(self.line)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.cutoffLabel1 = QtGui.QLabel(self.groupBox_4)
        self.cutoffLabel1.setEnabled(False)
        self.cutoffLabel1.setObjectName("cutoffLabel1")
        self.horizontalLayout_21.addWidget(self.cutoffLabel1)
        self.cutoffSpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.cutoffSpinBox.setEnabled(False)
        self.cutoffSpinBox.setMaximum(49)
        self.cutoffSpinBox.setProperty("value", 10)
        self.cutoffSpinBox.setObjectName("cutoffSpinBox")
        self.horizontalLayout_21.addWidget(self.cutoffSpinBox)
        self.cutoffLabel2 = QtGui.QLabel(self.groupBox_4)
        self.cutoffLabel2.setEnabled(False)
        self.cutoffLabel2.setObjectName("cutoffLabel2")
        self.horizontalLayout_21.addWidget(self.cutoffLabel2)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem18)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_22.addWidget(self.label_16)
        self.masterCurveComboBox = QtGui.QComboBox(self.groupBox_4)
        self.masterCurveComboBox.setObjectName("masterCurveComboBox")
        self.masterCurveComboBox.addItem("")
        self.masterCurveComboBox.addItem("")
        self.masterCurveComboBox.addItem("")
        self.horizontalLayout_22.addWidget(self.masterCurveComboBox)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem19)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.smoothingCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.smoothingCheckBox.setObjectName("smoothingCheckBox")
        self.horizontalLayout_2.addWidget(self.smoothingCheckBox)
        self.smoothingComboBox = QtGui.QComboBox(self.groupBox_4)
        self.smoothingComboBox.setEnabled(False)
        self.smoothingComboBox.setObjectName("smoothingComboBox")
        self.smoothingComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.smoothingComboBox)
        self.smoothingSpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.smoothingSpinBox.setEnabled(False)
        self.smoothingSpinBox.setMaximum(1000)
        self.smoothingSpinBox.setProperty("value", 40)
        self.smoothingSpinBox.setObjectName("smoothingSpinBox")
        self.horizontalLayout_2.addWidget(self.smoothingSpinBox)
        self.smoothingLabel = QtGui.QLabel(self.groupBox_4)
        self.smoothingLabel.setEnabled(False)
        self.smoothingLabel.setObjectName("smoothingLabel")
        self.horizontalLayout_2.addWidget(self.smoothingLabel)
        self.smoothingSpinBox2 = QtGui.QSpinBox(self.groupBox_4)
        self.smoothingSpinBox2.setEnabled(False)
        self.smoothingSpinBox2.setMinimum(1)
        self.smoothingSpinBox2.setMaximum(5)
        self.smoothingSpinBox2.setObjectName("smoothingSpinBox2")
        self.horizontalLayout_2.addWidget(self.smoothingSpinBox2)
        self.smoothingLabel2 = QtGui.QLabel(self.groupBox_4)
        self.smoothingLabel2.setEnabled(False)
        self.smoothingLabel2.setObjectName("smoothingLabel2")
        self.horizontalLayout_2.addWidget(self.smoothingLabel2)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem20)
        self.calculateHVSR = QtGui.QPushButton(self.groupBox_4)
        self.calculateHVSR.setObjectName("calculateHVSR")
        self.horizontalLayout_2.addWidget(self.calculateHVSR)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_8 = QtGui.QGroupBox(self.htovTab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_9 = QtGui.QLabel(self.groupBox_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_18.addWidget(self.label_9)
        self.xAxisMinSpinBox = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.xAxisMinSpinBox.setProperty("value", 0.5)
        self.xAxisMinSpinBox.setObjectName("xAxisMinSpinBox")
        self.horizontalLayout_18.addWidget(self.xAxisMinSpinBox)
        self.label_10 = QtGui.QLabel(self.groupBox_8)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        self.xAxisMaxSpinBox = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.xAxisMaxSpinBox.setProperty("value", 10.0)
        self.xAxisMaxSpinBox.setObjectName("xAxisMaxSpinBox")
        self.horizontalLayout_18.addWidget(self.xAxisMaxSpinBox)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem21)
        self.xAxisLogCheckBox = QtGui.QCheckBox(self.groupBox_8)
        self.xAxisLogCheckBox.setChecked(True)
        self.xAxisLogCheckBox.setObjectName("xAxisLogCheckBox")
        self.horizontalLayout_18.addWidget(self.xAxisLogCheckBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_19.addWidget(self.label_11)
        self.yAxisMinSpinBox = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.yAxisMinSpinBox.setObjectName("yAxisMinSpinBox")
        self.horizontalLayout_19.addWidget(self.yAxisMinSpinBox)
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_19.addWidget(self.label_12)
        self.yAxisMaxSpinBox = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.yAxisMaxSpinBox.setMaximum(999.0)
        self.yAxisMaxSpinBox.setProperty("value", 50.0)
        self.yAxisMaxSpinBox.setObjectName("yAxisMaxSpinBox")
        self.horizontalLayout_19.addWidget(self.yAxisMaxSpinBox)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem22)
        self.yAxisLogCheckBox = QtGui.QCheckBox(self.groupBox_8)
        self.yAxisLogCheckBox.setObjectName("yAxisLogCheckBox")
        self.horizontalLayout_19.addWidget(self.yAxisLogCheckBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem23)
        self.savePlotButton = QtGui.QPushButton(self.groupBox_8)
        self.savePlotButton.setEnabled(True)
        self.savePlotButton.setObjectName("savePlotButton")
        self.horizontalLayout_20.addWidget(self.savePlotButton)
        self.applyChangesToPlotButton = QtGui.QPushButton(self.groupBox_8)
        self.applyChangesToPlotButton.setObjectName("applyChangesToPlotButton")
        self.horizontalLayout_20.addWidget(self.applyChangesToPlotButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        self.verticalLayout_17.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.htovTab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label = QtGui.QLabel(self.groupBox_9)
        self.label.setObjectName("label")
        self.horizontalLayout_27.addWidget(self.label)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem24)
        self.verticalLayout_18.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem25)
        self.batchProcessingButton = QtGui.QPushButton(self.groupBox_9)
        self.batchProcessingButton.setObjectName("batchProcessingButton")
        self.horizontalLayout_26.addWidget(self.batchProcessingButton)
        self.verticalLayout_18.addLayout(self.horizontalLayout_26)
        self.verticalLayout_17.addWidget(self.groupBox_9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_17)
        self.menuTabWidget.addTab(self.htovTab, "")
        self.verticalLayout_12.addWidget(self.MainSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.plotTabWidget.setCurrentIndex(0)
        self.menuTabWidget.setCurrentIndex(0)
        self.spectraMethodStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "H/V Toolbox", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Raw Data", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Edited Data", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.hvTab), QtGui.QApplication.translate("MainWindow", "H/V Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFileButton.setText(QtGui.QApplication.translate("MainWindow", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTabWidget.setTabText(self.menuTabWidget.indexOf(self.loadDataTab), QtGui.QApplication.translate("MainWindow", "Load Data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Cut Traces", None, QtGui.QApplication.UnicodeUTF8))
        self.starttimeLabel.setText(QtGui.QApplication.translate("MainWindow", "Starttime", None, QtGui.QApplication.UnicodeUTF8))
        self.starttimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd.MM.yy HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.endtimeLabel.setText(QtGui.QApplication.translate("MainWindow", "Endtime", None, QtGui.QApplication.UnicodeUTF8))
        self.endtimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd.MM.yy HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Filter Traces", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Lower Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.highpassLabel.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Upper Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.lowpassLabel.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.cornersLabel.setText(QtGui.QApplication.translate("MainWindow", "Corners", None, QtGui.QApplication.UnicodeUTF8))
        self.zerophaseCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Zero Phase Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Resample Traces", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "New Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.saveEditedDataButton.setText(QtGui.QApplication.translate("MainWindow", "Save edited Data", None, QtGui.QApplication.UnicodeUTF8))
        self.editDataButton.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTabWidget.setTabText(self.menuTabWidget.indexOf(self.editDataTab), QtGui.QApplication.translate("MainWindow", "Edit Data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Calibration of the Z-Detector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Window length in samples for the Z-Detector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Threshold in percentile", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Window Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Window Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.findNoiseButton.setText(QtGui.QApplication.translate("MainWindow", "Autodetect", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTabWidget.setTabText(self.menuTabWidget.indexOf(self.findNoiseTab), QtGui.QApplication.translate("MainWindow", "Find Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "HVSR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Method to calculate the spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.spectraMethodComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Multitaper", None, QtGui.QApplication.UnicodeUTF8))
        self.spectraMethodComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Sine Multitaper", None, QtGui.QApplication.UnicodeUTF8))
        self.spectraMethodComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Single Taper", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Time-halfbandwith product", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Number of tapers", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "auto", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(8, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(9, QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersComboBox.setItemText(10, QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.multitaperPadCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Pad with zeros", None, QtGui.QApplication.UnicodeUTF8))
        self.nfftLabel.setText(QtGui.QApplication.translate("MainWindow", "new sample count:", None, QtGui.QApplication.UnicodeUTF8))
        self.quadraticCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Quadratic Multitaper", None, QtGui.QApplication.UnicodeUTF8))
        self.adaptiveCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Adaptive", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Number of tapers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "0 means adaptive for each frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Number of iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Degree of smoothing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Choose Taper", None, QtGui.QApplication.UnicodeUTF8))
        self.singleTaperComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Bartlett", None, QtGui.QApplication.UnicodeUTF8))
        self.singleTaperComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Blackman", None, QtGui.QApplication.UnicodeUTF8))
        self.singleTaperComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Boxcar", None, QtGui.QApplication.UnicodeUTF8))
        self.singleTaperComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Hamming", None, QtGui.QApplication.UnicodeUTF8))
        self.singleTaperComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Hanning", None, QtGui.QApplication.UnicodeUTF8))
        self.singleTaperComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Kaiser (beta=14)", None, QtGui.QApplication.UnicodeUTF8))
        self.cutoffLabel1.setText(QtGui.QApplication.translate("MainWindow", "Discard top and bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.cutoffLabel2.setText(QtGui.QApplication.translate("MainWindow", "percent for each frequency.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Method for the master HVSR curve:", None, QtGui.QApplication.UnicodeUTF8))
        self.masterCurveComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Median and 25 and 75 % Quantiles", None, QtGui.QApplication.UnicodeUTF8))
        self.masterCurveComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Mean and Standard Deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.masterCurveComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Geometric Mean and Standard Deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothingCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Smoothing", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothingComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Konno-Ohmachi", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothingLabel.setText(QtGui.QApplication.translate("MainWindow", "smoothing constant", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothingLabel2.setText(QtGui.QApplication.translate("MainWindow", "times", None, QtGui.QApplication.UnicodeUTF8))
        self.calculateHVSR.setText(QtGui.QApplication.translate("MainWindow", "Calculate H/V", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "x Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.xAxisLogCheckBox.setText(QtGui.QApplication.translate("MainWindow", "logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "y Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.yAxisLogCheckBox.setText(QtGui.QApplication.translate("MainWindow", "logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.savePlotButton.setText(QtGui.QApplication.translate("MainWindow", "Save Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.applyChangesToPlotButton.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Batch processing", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "To use the same settings on several files click here.", None, QtGui.QApplication.UnicodeUTF8))
        self.batchProcessingButton.setText(QtGui.QApplication.translate("MainWindow", "Batch", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTabWidget.setTabText(self.menuTabWidget.indexOf(self.htovTab), QtGui.QApplication.translate("MainWindow", "H/V", None, QtGui.QApplication.UnicodeUTF8))

from qt4mplcanvas import Qt4MplCanvas
