# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_plot_dialog.ui'
#
# Created: Thu Jul 29 19:21:23 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SavePlotDialog(object):
    def setupUi(self, SavePlotDialog):
        SavePlotDialog.setObjectName("SavePlotDialog")
        SavePlotDialog.resize(509, 219)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SavePlotDialog.sizePolicy().hasHeightForWidth())
        SavePlotDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(SavePlotDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(SavePlotDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.filenameLineEdit = QtGui.QLineEdit(SavePlotDialog)
        self.filenameLineEdit.setObjectName("filenameLineEdit")
        self.horizontalLayout_2.addWidget(self.filenameLineEdit)
        self.fileDialogButton = QtGui.QPushButton(SavePlotDialog)
        self.fileDialogButton.setObjectName("fileDialogButton")
        self.horizontalLayout_2.addWidget(self.fileDialogButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(SavePlotDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widthSpinBox = QtGui.QSpinBox(self.groupBox)
        self.widthSpinBox.setMinimum(100)
        self.widthSpinBox.setMaximum(4000)
        self.widthSpinBox.setProperty("value", 800)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.horizontalLayout_3.addWidget(self.widthSpinBox)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.dpiSpinBox = QtGui.QSpinBox(self.groupBox)
        self.dpiSpinBox.setMinimum(1)
        self.dpiSpinBox.setMaximum(1000)
        self.dpiSpinBox.setProperty("value", 100)
        self.dpiSpinBox.setObjectName("dpiSpinBox")
        self.horizontalLayout_3.addWidget(self.dpiSpinBox)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.heightSpinBox = QtGui.QSpinBox(self.groupBox)
        self.heightSpinBox.setMinimum(100)
        self.heightSpinBox.setMaximum(4000)
        self.heightSpinBox.setProperty("value", 600)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self.horizontalLayout_4.addWidget(self.heightSpinBox)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cancelButton = QtGui.QPushButton(SavePlotDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.okButton = QtGui.QPushButton(SavePlotDialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SavePlotDialog)
        QtCore.QMetaObject.connectSlotsByName(SavePlotDialog)

    def retranslateUi(self, SavePlotDialog):
        SavePlotDialog.setWindowTitle(QtGui.QApplication.translate("SavePlotDialog", "Save Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SavePlotDialog", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDialogButton.setText(QtGui.QApplication.translate("SavePlotDialog", "Choose File", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SavePlotDialog", "Image Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SavePlotDialog", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SavePlotDialog", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SavePlotDialog", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("SavePlotDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("SavePlotDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))

