# Python stubs generated by omniidl from ..\..\..\..\..\idl\COS\CosPersistencePOM.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "CosPersistencePID.idl"
import CosPersistencePID_idl
_0_CosPersistencePID = omniORB.openModule("CosPersistencePID")
_0_CosPersistencePID__POA = omniORB.openModule("CosPersistencePID__POA")
# #include "CosPersistencePDS.idl"
import CosPersistencePDS_idl
_0_CosPersistencePDS = omniORB.openModule("CosPersistencePDS")
_0_CosPersistencePDS__POA = omniORB.openModule("CosPersistencePDS__POA")

#
# Start of module "CosPersistencePOM"
#
__name__ = "CosPersistencePOM"
_0_CosPersistencePOM = omniORB.openModule("CosPersistencePOM", r"..\..\..\..\..\idl\COS\CosPersistencePOM.idl")
_0_CosPersistencePOM__POA = omniORB.openModule("CosPersistencePOM__POA", r"..\..\..\..\..\idl\COS\CosPersistencePOM.idl")


# interface POM
_0_CosPersistencePOM._d_POM = (omniORB.tcInternal.tv_objref, "IDL:omg.org/CosPersistencePOM/POM:1.0", "POM")
omniORB.typeMapping["IDL:omg.org/CosPersistencePOM/POM:1.0"] = _0_CosPersistencePOM._d_POM
_0_CosPersistencePOM.POM = omniORB.newEmptyClass()
class POM :
    _NP_RepositoryId = _0_CosPersistencePOM._d_POM[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_CosPersistencePOM.POM = POM
_0_CosPersistencePOM._tc_POM = omniORB.tcInternal.createTypeCode(_0_CosPersistencePOM._d_POM)
omniORB.registerType(POM._NP_RepositoryId, _0_CosPersistencePOM._d_POM, _0_CosPersistencePOM._tc_POM)

# POM operations and attributes
POM._d_connect = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (omniORB.typeMapping["IDL:omg.org/CosPersistencePDS/PDS:1.0"], ), None)
POM._d_disconnect = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (), None)
POM._d_store = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (), None)
POM._d_restore = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (), None)
POM._d_delete = ((omniORB.typeMapping["IDL:omg.org/CORBA/Object:1.0"], omniORB.typeMapping["IDL:omg.org/CosPersistencePID/PID:1.0"]), (), None)

# POM object reference
class _objref_POM (CORBA.Object):
    _NP_RepositoryId = POM._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def connect(self, *args):
        return _omnipy.invoke(self, "connect", _0_CosPersistencePOM.POM._d_connect, args)

    def disconnect(self, *args):
        return _omnipy.invoke(self, "disconnect", _0_CosPersistencePOM.POM._d_disconnect, args)

    def store(self, *args):
        return _omnipy.invoke(self, "store", _0_CosPersistencePOM.POM._d_store, args)

    def restore(self, *args):
        return _omnipy.invoke(self, "restore", _0_CosPersistencePOM.POM._d_restore, args)

    def delete(self, *args):
        return _omnipy.invoke(self, "delete", _0_CosPersistencePOM.POM._d_delete, args)

    __methods__ = ["connect", "disconnect", "store", "restore", "delete"] + CORBA.Object.__methods__

omniORB.registerObjref(POM._NP_RepositoryId, _objref_POM)
_0_CosPersistencePOM._objref_POM = _objref_POM
del POM, _objref_POM

# POM skeleton
__name__ = "CosPersistencePOM__POA"
class POM (PortableServer.Servant):
    _NP_RepositoryId = _0_CosPersistencePOM.POM._NP_RepositoryId


    _omni_op_d = {"connect": _0_CosPersistencePOM.POM._d_connect, "disconnect": _0_CosPersistencePOM.POM._d_disconnect, "store": _0_CosPersistencePOM.POM._d_store, "restore": _0_CosPersistencePOM.POM._d_restore, "delete": _0_CosPersistencePOM.POM._d_delete}

POM._omni_skeleton = POM
_0_CosPersistencePOM__POA.POM = POM
omniORB.registerSkeleton(POM._NP_RepositoryId, POM)
del POM
__name__ = "CosPersistencePOM"

#
# End of module "CosPersistencePOM"
#
__name__ = "CosPersistencePOM_idl"

_exported_modules = ( "CosPersistencePOM", )

# The end.
