# DO NOT EDIT THIS FILE!
#
# Python module CosTime generated by omniidl

import omniORB
omniORB.updateModule("CosTime")

# ** 1. Stub files contributing to this module
import CosTime_idl

# ** 2. Sub-modules

# ** 3. End
