# DO NOT EDIT THIS FILE!
#
# Python module CosExternalizationContainment__POA generated by omniidl

import omniORB
omniORB.updateModule("CosExternalizationContainment__POA")

# ** 1. Stub files contributing to this module
import CosExternalizationContainment_idl

# ** 2. Sub-modules

# ** 3. End
