# DO NOT EDIT THIS FILE!
#
# Python module CosRelationships__POA generated by omniidl

import omniORB
omniORB.updateModule("CosRelationships__POA")

# ** 1. Stub files contributing to this module
import CosRelationships_idl

# ** 2. Sub-modules

# ** 3. End
