# DO NOT EDIT THIS FILE!
#
# Python module CosLifeCycleContainment generated by omniidl

import omniORB
omniORB.updateModule("CosLifeCycleContainment")

# ** 1. Stub files contributing to this module
import CosLifeCycleContainment_idl

# ** 2. Sub-modules

# ** 3. End
