.\" -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OBSPY-FLINN-ENGDAHL 1 "November 4, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7) and groff_man(7)
.\" .SH        section heading
.\" .SS        secondary section heading
.\"
.\"
.\" To preview this page as plain text: nroff -man obspy-plot
.\"
.SH NAME
obspy-flinn-engdahl \- Get Flinn-Engahl region name from longitude and latitude
.SH SYNOPSIS
.B obspy-flinn-engdahl
.RI "longitude latitude"
.SH DESCRIPTION
Script to print Flinn-Engahl region name from longitude and latitude. Longitude and latitude are given as decimal degrees, positive for East/North, negative for West/South.
.br
.sp 1
.SH AUTHOR
obspy-flinn-engdahl was written by the ObsPy Development Team <devs@obspy.org>. This manual page was written by ObsPy Development Team <devs@obspy.org> for the Debian project (but may be used by others).
