.\" -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OBSPY-REFTEK-RESCUE 1 "June 30, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7) and groff_man(7)
.\" .SH        section heading
.\" .SS        secondary section heading
.\"
.\"
.\" To preview this page as plain text: nroff -man obspy-runtests
.\"
.SH NAME
obspy-reftek-rescue \- Restore REFTEK data from raw binary data dumps.
.SH SYNOPSIS
.B obspy-reftek-rescue
.RI [ options ]
.SH DESCRIPTION
This program is intended for restoring REFTEK 130-01 packets from raw binary dumped disk images, e.g. from formatted but not yet (completely) overwritten storage media. The raw dumped data is searched for a header pattern consisting of experiment number, year and REFTEK DAS ID.  Found packets are written to one file per recording event like in normal acquisition.
.SH OPTIONS
All options including basic examples are available by calling obspy-reftek-rescue -h
.br
.sp 1
.B \-h
Display extensive help and all other available options
.SH AUTHOR
obspy-reftek-rescue was written by the ObsPy Development Team <devs@obspy.org>. This manual page was written by the ObsPy Development Team <devs@obspy.org> for the Debian project (but may be used by others).
