# DO NOT EDIT THIS FILE!
#
# Python module CosTypedNotifyComm generated by omniidl

import omniORB
omniORB.updateModule("CosTypedNotifyComm")

# ** 1. Stub files contributing to this module
import CosTypedNotifyComm_idl

# ** 2. Sub-modules

# ** 3. End
