# DO NOT EDIT THIS FILE!
#
# Python module CosPersistencePDS generated by omniidl

import omniORB
omniORB.updateModule("CosPersistencePDS")

# ** 1. Stub files contributing to this module
import CosPersistencePDS_idl

# ** 2. Sub-modules

# ** 3. End
