# DO NOT EDIT THIS FILE!
#
# Python module CosPropertyService__POA generated by omniidl

import omniORB
omniORB.updateModule("CosPropertyService__POA")

# ** 1. Stub files contributing to this module
import CosPropertyService_idl

# ** 2. Sub-modules

# ** 3. End
