# DO NOT EDIT THIS FILE!
#
# Python module CosObjectIdentity generated by omniidl

import omniORB
omniORB.updateModule("CosObjectIdentity")

# ** 1. Stub files contributing to this module
import CosObjectIdentity_idl

# ** 2. Sub-modules

# ** 3. End
