# DO NOT EDIT THIS FILE!
#
# Python module CosCollection__POA generated by omniidl

import omniORB
omniORB.updateModule("CosCollection__POA")

# ** 1. Stub files contributing to this module
import CosCollection_idl

# ** 2. Sub-modules

# ** 3. End
