package:
  name: suds
  version: !!str 0.4

source:
  fn: suds-0.4.tar.gz
  url: https://pypi.python.org/packages/source/s/suds/suds-0.4.tar.gz
  md5: b7502de662341ed7275b673e6bd73191
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - suds = suds:main
    #
    # Would create an entry point called suds that calls suds.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - suds.xsd
    - suds.mx
    - suds.transport
    - suds.umx
    - suds.bindings
    - suds
    - suds.sax

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://fedorahosted.org/suds
  license: LGPLv3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
