# Python stubs generated by omniidl from ..\..\..\..\..\idl\COS\CosLifeCycleReference.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "corbaidl.idl"
import corbaidl_idl
_0_CORBA = omniORB.openModule("CORBA")
_0_CORBA__POA = omniORB.openModule("CORBA__POA")
# #include "boxes.idl"
import boxes_idl
_0_CORBA = omniORB.openModule("CORBA")
_0_CORBA__POA = omniORB.openModule("CORBA__POA")
# #include "ir.idl"
import ir_idl
_0_CORBA = omniORB.openModule("CORBA")
_0_CORBA__POA = omniORB.openModule("CORBA__POA")
# #include "CosObjectIdentity.idl"
import CosObjectIdentity_idl
_0_CosObjectIdentity = omniORB.openModule("CosObjectIdentity")
_0_CosObjectIdentity__POA = omniORB.openModule("CosObjectIdentity__POA")
# #include "CosRelationships.idl"
import CosRelationships_idl
_0_CosRelationships = omniORB.openModule("CosRelationships")
_0_CosRelationships__POA = omniORB.openModule("CosRelationships__POA")
# #include "CosGraphs.idl"
import CosGraphs_idl
_0_CosGraphs = omniORB.openModule("CosGraphs")
_0_CosGraphs__POA = omniORB.openModule("CosGraphs__POA")
# #include "CosReference.idl"
import CosReference_idl
_0_CosReference = omniORB.openModule("CosReference")
_0_CosReference__POA = omniORB.openModule("CosReference__POA")
# #include "CosNaming.idl"
import CosNaming_idl
_0_CosNaming = omniORB.openModule("CosNaming")
_0_CosNaming__POA = omniORB.openModule("CosNaming__POA")
# #include "CosLifeCycle.idl"
import CosLifeCycle_idl
_0_CosLifeCycle = omniORB.openModule("CosLifeCycle")
_0_CosLifeCycle__POA = omniORB.openModule("CosLifeCycle__POA")
# #include "CosCompoundLifeCycle.idl"
import CosCompoundLifeCycle_idl
_0_CosCompoundLifeCycle = omniORB.openModule("CosCompoundLifeCycle")
_0_CosCompoundLifeCycle__POA = omniORB.openModule("CosCompoundLifeCycle__POA")

#
# Start of module "CosLifeCycleReference"
#
__name__ = "CosLifeCycleReference"
_0_CosLifeCycleReference = omniORB.openModule("CosLifeCycleReference", r"..\..\..\..\..\idl\COS\CosLifeCycleReference.idl")
_0_CosLifeCycleReference__POA = omniORB.openModule("CosLifeCycleReference__POA", r"..\..\..\..\..\idl\COS\CosLifeCycleReference.idl")


# interface Relationship
_0_CosLifeCycleReference._d_Relationship = (omniORB.tcInternal.tv_objref, "IDL:omg.org/CosLifeCycleReference/Relationship:1.0", "Relationship")
omniORB.typeMapping["IDL:omg.org/CosLifeCycleReference/Relationship:1.0"] = _0_CosLifeCycleReference._d_Relationship
_0_CosLifeCycleReference.Relationship = omniORB.newEmptyClass()
class Relationship (_0_CosCompoundLifeCycle.Relationship, _0_CosReference.Relationship):
    _NP_RepositoryId = _0_CosLifeCycleReference._d_Relationship[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_CosLifeCycleReference.Relationship = Relationship
_0_CosLifeCycleReference._tc_Relationship = omniORB.tcInternal.createTypeCode(_0_CosLifeCycleReference._d_Relationship)
omniORB.registerType(Relationship._NP_RepositoryId, _0_CosLifeCycleReference._d_Relationship, _0_CosLifeCycleReference._tc_Relationship)

# Relationship object reference
class _objref_Relationship (_0_CosCompoundLifeCycle._objref_Relationship, _0_CosReference._objref_Relationship):
    _NP_RepositoryId = Relationship._NP_RepositoryId

    def __init__(self):
        _0_CosCompoundLifeCycle._objref_Relationship.__init__(self)
        _0_CosReference._objref_Relationship.__init__(self)

    __methods__ = [] + _0_CosCompoundLifeCycle._objref_Relationship.__methods__ + _0_CosReference._objref_Relationship.__methods__

omniORB.registerObjref(Relationship._NP_RepositoryId, _objref_Relationship)
_0_CosLifeCycleReference._objref_Relationship = _objref_Relationship
del Relationship, _objref_Relationship

# Relationship skeleton
__name__ = "CosLifeCycleReference__POA"
class Relationship (_0_CosCompoundLifeCycle__POA.Relationship, _0_CosReference__POA.Relationship):
    _NP_RepositoryId = _0_CosLifeCycleReference.Relationship._NP_RepositoryId


    _omni_op_d = {}
    _omni_op_d.update(_0_CosCompoundLifeCycle__POA.Relationship._omni_op_d)
    _omni_op_d.update(_0_CosReference__POA.Relationship._omni_op_d)

Relationship._omni_skeleton = Relationship
_0_CosLifeCycleReference__POA.Relationship = Relationship
omniORB.registerSkeleton(Relationship._NP_RepositoryId, Relationship)
del Relationship
__name__ = "CosLifeCycleReference"

# interface ReferencesRole
_0_CosLifeCycleReference._d_ReferencesRole = (omniORB.tcInternal.tv_objref, "IDL:omg.org/CosLifeCycleReference/ReferencesRole:1.0", "ReferencesRole")
omniORB.typeMapping["IDL:omg.org/CosLifeCycleReference/ReferencesRole:1.0"] = _0_CosLifeCycleReference._d_ReferencesRole
_0_CosLifeCycleReference.ReferencesRole = omniORB.newEmptyClass()
class ReferencesRole (_0_CosCompoundLifeCycle.Role, _0_CosReference.ReferencesRole):
    _NP_RepositoryId = _0_CosLifeCycleReference._d_ReferencesRole[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_CosLifeCycleReference.ReferencesRole = ReferencesRole
_0_CosLifeCycleReference._tc_ReferencesRole = omniORB.tcInternal.createTypeCode(_0_CosLifeCycleReference._d_ReferencesRole)
omniORB.registerType(ReferencesRole._NP_RepositoryId, _0_CosLifeCycleReference._d_ReferencesRole, _0_CosLifeCycleReference._tc_ReferencesRole)

# ReferencesRole object reference
class _objref_ReferencesRole (_0_CosCompoundLifeCycle._objref_Role, _0_CosReference._objref_ReferencesRole):
    _NP_RepositoryId = ReferencesRole._NP_RepositoryId

    def __init__(self):
        _0_CosCompoundLifeCycle._objref_Role.__init__(self)
        _0_CosReference._objref_ReferencesRole.__init__(self)

    __methods__ = [] + _0_CosCompoundLifeCycle._objref_Role.__methods__ + _0_CosReference._objref_ReferencesRole.__methods__

omniORB.registerObjref(ReferencesRole._NP_RepositoryId, _objref_ReferencesRole)
_0_CosLifeCycleReference._objref_ReferencesRole = _objref_ReferencesRole
del ReferencesRole, _objref_ReferencesRole

# ReferencesRole skeleton
__name__ = "CosLifeCycleReference__POA"
class ReferencesRole (_0_CosCompoundLifeCycle__POA.Role, _0_CosReference__POA.ReferencesRole):
    _NP_RepositoryId = _0_CosLifeCycleReference.ReferencesRole._NP_RepositoryId


    _omni_op_d = {}
    _omni_op_d.update(_0_CosCompoundLifeCycle__POA.Role._omni_op_d)
    _omni_op_d.update(_0_CosReference__POA.ReferencesRole._omni_op_d)

ReferencesRole._omni_skeleton = ReferencesRole
_0_CosLifeCycleReference__POA.ReferencesRole = ReferencesRole
omniORB.registerSkeleton(ReferencesRole._NP_RepositoryId, ReferencesRole)
del ReferencesRole
__name__ = "CosLifeCycleReference"

# interface ReferencedByRole
_0_CosLifeCycleReference._d_ReferencedByRole = (omniORB.tcInternal.tv_objref, "IDL:omg.org/CosLifeCycleReference/ReferencedByRole:1.0", "ReferencedByRole")
omniORB.typeMapping["IDL:omg.org/CosLifeCycleReference/ReferencedByRole:1.0"] = _0_CosLifeCycleReference._d_ReferencedByRole
_0_CosLifeCycleReference.ReferencedByRole = omniORB.newEmptyClass()
class ReferencedByRole (_0_CosCompoundLifeCycle.Role, _0_CosReference.ReferencedByRole):
    _NP_RepositoryId = _0_CosLifeCycleReference._d_ReferencedByRole[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_CosLifeCycleReference.ReferencedByRole = ReferencedByRole
_0_CosLifeCycleReference._tc_ReferencedByRole = omniORB.tcInternal.createTypeCode(_0_CosLifeCycleReference._d_ReferencedByRole)
omniORB.registerType(ReferencedByRole._NP_RepositoryId, _0_CosLifeCycleReference._d_ReferencedByRole, _0_CosLifeCycleReference._tc_ReferencedByRole)

# ReferencedByRole object reference
class _objref_ReferencedByRole (_0_CosCompoundLifeCycle._objref_Role, _0_CosReference._objref_ReferencedByRole):
    _NP_RepositoryId = ReferencedByRole._NP_RepositoryId

    def __init__(self):
        _0_CosCompoundLifeCycle._objref_Role.__init__(self)
        _0_CosReference._objref_ReferencedByRole.__init__(self)

    __methods__ = [] + _0_CosCompoundLifeCycle._objref_Role.__methods__ + _0_CosReference._objref_ReferencedByRole.__methods__

omniORB.registerObjref(ReferencedByRole._NP_RepositoryId, _objref_ReferencedByRole)
_0_CosLifeCycleReference._objref_ReferencedByRole = _objref_ReferencedByRole
del ReferencedByRole, _objref_ReferencedByRole

# ReferencedByRole skeleton
__name__ = "CosLifeCycleReference__POA"
class ReferencedByRole (_0_CosCompoundLifeCycle__POA.Role, _0_CosReference__POA.ReferencedByRole):
    _NP_RepositoryId = _0_CosLifeCycleReference.ReferencedByRole._NP_RepositoryId


    _omni_op_d = {}
    _omni_op_d.update(_0_CosCompoundLifeCycle__POA.Role._omni_op_d)
    _omni_op_d.update(_0_CosReference__POA.ReferencedByRole._omni_op_d)

ReferencedByRole._omni_skeleton = ReferencedByRole
_0_CosLifeCycleReference__POA.ReferencedByRole = ReferencedByRole
omniORB.registerSkeleton(ReferencedByRole._NP_RepositoryId, ReferencedByRole)
del ReferencedByRole
__name__ = "CosLifeCycleReference"

#
# End of module "CosLifeCycleReference"
#
__name__ = "CosLifeCycleReference_idl"

_exported_modules = ( "CosLifeCycleReference", )

# The end.
